import {useEffect,useRef,useState} from 'react';
import {createStudio} from './studio';
import {finishes,initialDesign,layoutNames,layouts,readDesign,surfaceNames,validDesign} from './design';
import type {Design,Surface} from './design';
import './configurator.css';
type Saved={id:string;name:string;design:Design;image:string};
const storageKey='eme-spatial-kitchen65';
function loadSaved():Saved[]{try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(value)?value.filter(v=>v&&typeof v.id==='string'&&typeof v.name==='string'&&typeof v.image==='string').slice(0,4).map(v=>({...v,design:validDesign(v.design)})):[]}catch{return []}}
export default function KitchenConfigurator(){
 const host=useRef<HTMLDivElement>(null),studio=useRef<ReturnType<typeof createStudio>|null>(null);const [design,setDesign]=useState<Design>(readDesign);const latest=useRef(design);latest.current=design;
 const [ready,setReady]=useState(false),[error,setError]=useState(false),[tab,setTab]=useState('layout'),[surface,setSurface]=useState<Surface>('cabinet'),[saved,setSaved]=useState<Saved[]>(loadSaved),[notice,setNotice]=useState(''),[compare,setCompare]=useState(false),[reference,setReference]=useState<Design|null>(null),[exporting,setExporting]=useState(false);
 const effective=compare&&reference?reference:design;
 useEffect(()=>{let api:ReturnType<typeof createStudio>|null=null;try{api=createStudio(host.current!,s=>{setTab('materials');setSurface(s)},()=>setReady(true),()=>setError(true));studio.current=api;api.apply(latest.current)}catch{setError(true)}return()=>{api?.dispose();studio.current=null}},[]);
 useEffect(()=>{studio.current?.apply(effective)},[effective]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 const update=(patch:Partial<Design>)=>{setCompare(false);setDesign(d=>({...d,...patch}))};
 const persist=(items:Saved[])=>{try{localStorage.setItem(storageKey,JSON.stringify(items));setSaved(items);return true}catch{setNotice('Não foi possível salvar neste navegador. Você ainda pode baixar a imagem ou copiar o link.');return false}};
 const save=()=>{if(!ready)return;const item:Saved={id:crypto.randomUUID(),name:`${layoutNames[design.layout]} · ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`,design:{...design},image:studio.current?.thumbnail()||''};if(persist([item,...saved].slice(0,4))){setNotice('Proposta salva neste navegador. As quatro mais recentes ficam disponíveis.');setTab('saved');setReference({...design});setCompare(false)}};
 const download=async()=>{setExporting(true);try{const blob=await studio.current?.download();if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`EME-Spatial-cozinha-${effective.layout}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice('Imagem preparada para download.')}catch{setNotice('Não foi possível gerar a imagem. Tente novamente.')}finally{setExporting(false)}};
 const share=async()=>{const url=new URL(location.href);url.searchParams.set('design',JSON.stringify(effective));try{await navigator.clipboard.writeText(url.href);setNotice('Link copiado com o layout, materiais e iluminação escolhidos.')}catch{setNotice('Não foi possível copiar automaticamente. A combinação foi colocada no endereço da página.');history.replaceState(null,'',url)}};
 return <main className="c65">
  <header className="c65-header"><a className="c65-brand" href="/">EME <b>SPATIAL</b></a><span>ESTÚDIO DE POSSIBILIDADES</span><a className="c65-back" href="/galeria-m.html">Ver imagens do projeto ↗</a></header>
  <div className="c65-workspace">
   <section className={`c65-stage${effective.day>65?' c65-night':''}`} aria-label="Ambiente interativo"><div className="c65-canvas" ref={host} data-testid="configurator-canvas"/>
    <div className="c65-title"><span>APARTAMENTO 14 / TORRE M</span><h1>Seu espaço.<br/><em>Do seu jeito.</em></h1><p>Cozinha e jantar · estudo de interiores</p></div>
    {!ready&&!error&&<div className="c65-loading" role="status"><i/>Preparando seu ambiente…<small>Carregando somente a cozinha e a sala.</small></div>}
    {error&&<div className="c65-loading" role="alert"><strong>Não foi possível abrir o 3D.</strong><p>Recarregue a página ou conheça as imagens do ambiente.</p><button onClick={()=>location.reload()}>Tentar novamente</button><a href="/galeria-m.html">Abrir galeria</a></div>}
    {compare&&<div className="c65-compare-badge">Visualizando a referência salva</div>}
    <div className="c65-views" role="group" aria-label="Enquadramento"><button disabled={!ready} onClick={()=>studio.current?.view('general')}>Visão geral</button><button disabled={!ready} onClick={()=>studio.current?.view('kitchen')}>Cozinha</button><button disabled={!ready} onClick={()=>studio.current?.view('dining')}>Jantar</button></div>
    <div className="c65-hint">Arraste para girar · Aproxime com a roda · Clique em um acabamento</div>
   </section>
   <aside className="c65-panel" aria-label="Configurar ambiente"><div className="c65-panel-heading"><span>01 — EXPLORAR</span><h2>Uma ideia.<br/> Suas possibilidades.</h2></div>
    <nav className="c65-tabs" aria-label="Opções do configurador">{[['layout','Layout'],['materials','Materiais'],['light','Luz'],['saved','Salvos']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}{id==='saved'&&saved.length>0&&<sup>{saved.length}</sup>}</button>)}</nav>
    <div className="c65-options">
     {tab==='layout'&&<><h3>Como você gosta de receber?</h3><p className="c65-description">Três propostas para explorar a cozinha integrada ao jantar.</p><div className="c65-layouts">{layouts.map((id,i)=><button key={id} disabled={!ready} aria-pressed={design.layout===id&&!compare} onClick={()=>update({layout:id})}><span className={`c65-plan ${id}`} aria-hidden="true"><i/><b/><em/></span><span><strong>{layoutNames[id]}</strong><small>{['Um centro para cozinhar e conversar.','Bancada conectada, espaço compartilhado.','Preparo lateral e área central livre.'][i]}</small></span><span className="c65-check">{design.layout===id?'✓':'↗'}</span></button>)}</div><p className="c65-note">Propostas visuais. Medidas, instalações e circulação precisam de validação no projeto executivo.</p></>}
     {tab==='materials'&&<><h3>Escolha o que quer transformar.</h3><div className="c65-surfaces">{(Object.keys(surfaceNames) as Surface[]).map(s=><button key={s} aria-pressed={surface===s} onClick={()=>setSurface(s)}>{surfaceNames[s]}</button>)}</div><p className="c65-description">{surfaceNames[surface]} · selecione um acabamento.</p><div className="c65-finishes">{finishes[surface].map((f,i)=><button disabled={!ready} key={f.name} aria-pressed={design[surface]===i&&!compare} onClick={()=>update({[surface]:i})}><span style={{backgroundColor:f.color}}>{design[surface]===i?'✓':''}</span><strong>{f.name}</strong></button>)}</div><p className="c65-note">Você também pode clicar diretamente nos armários, bancadas, piso ou estofados.</p></>}
     {tab==='light'&&<><h3>O ambiente muda com a luz.</h3><p className="c65-description">Compare a entrada de luz do dia com uma atmosfera noturna.</p><label className="c65-range" htmlFor="c65-day">Período do dia <strong>{design.day<35?'Dia':design.day<75?'Fim de tarde':'Noite'}</strong><input disabled={!ready} id="c65-day" type="range" min="0" max="100" value={design.day} onChange={e=>update({day:Number(e.target.value)})}/><span>Dia <b>Noite</b></span></label><label className="c65-switch"><span><strong>Luminárias acesas</strong><small>Pendente e iluminação de apoio.</small></span><input disabled={!ready} type="checkbox" checked={design.lights} onChange={e=>update({lights:e.target.checked})}/></label></>}
     {tab==='saved'&&<><h3>Suas combinações favoritas.</h3><p className="c65-description">Até quatro propostas salvas neste navegador.</p>{saved.length===0?<div className="c65-empty">Explore os acabamentos e use “Salvar proposta” para guardar sua primeira combinação.</div>:<div className="c65-saved">{saved.map(item=><article key={item.id}>{item.image&&<img src={item.image} alt={item.name}/>}<strong>{item.name}</strong><div><button onClick={()=>{setDesign(item.design);setCompare(false);setNotice('Proposta carregada.')}}>Abrir</button><button onClick={()=>{setReference(item.design);setCompare(true)}}>Comparar</button><button aria-label={`Excluir ${item.name}`} onClick={()=>persist(saved.filter(s=>s.id!==item.id))}>Excluir</button></div></article>)}</div>}</>}
    </div>
    <div className="c65-actions"><button className="c65-primary" disabled={!ready||compare} onClick={save}>Salvar proposta <span>＋</span></button><div><button disabled={!ready||exporting} onClick={download}>{exporting?'Preparando…':'Baixar imagem ↓'}</button><button disabled={!ready} onClick={share}>Copiar link ↗</button></div><div><button disabled={!ready} onClick={()=>{if(reference)setCompare(!compare);else{setReference({...design});setNotice('Referência definida. Altere materiais ou layout e clique em Comparar.')}}}>{compare?'Voltar à edição':reference?'Comparar A / B':'Definir referência A'}</button><button disabled={!ready} onClick={()=>{setDesign({...initialDesign});setCompare(false);studio.current?.view('general')}}>Restaurar</button></div></div>
   </aside>
  </div>
  <footer className="c65-footer"><span>EME Spatial · Conceitos que você pode explorar.</span><span>Visualização ilustrativa · Cozinha e jantar do apartamento 14</span></footer>
  {notice&&<div className="c65-toast" role="status">{notice}</div>}
 </main>
}
