import assert from 'node:assert/strict';
import * as T from 'three';
import {furnishMApartments44} from '../src/developments/mApartmentFurniture44.ts';
import {installDesign70,read70,save70,validate70,initial70,DESIGN_KEY} from '../src/developments/mDesign70.ts';
const floors=Array.from({length:22},()=>new T.Group());furnishMApartments44(floors,x=>x);
const source=floors[13],other=floors[10],before=new T.Box3().setFromObject(source),otherColors=[];
other.traverse(o=>{if(o.material)otherColors.push(o.material.color.getHex());});
const textures={finishWood:()=>{},finishStone:()=>{},finishLinen:()=>{}};
const api=installDesign70(source,x=>x,textures),clone=source.clone(true);
const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};
const draft={wood:1,fabric:1,accent:2,stone:1,table:'oval'};
api.apply(draft);api.apply(draft,clone);
assert.equal(data.size,0,'Preview must not save');assert.deepEqual(read70(storage),initial70);
let n=0;other.traverse(o=>{if(o.material)assert.equal(o.material.color.getHex(),otherColors[n++],'Other floor unchanged');});
clone.traverse(o=>{if(o.userData.table70)assert.equal(o.scale.z,.68);});
api.apply(initial70);assert(before.equals(new T.Box3().setFromObject(source)),'Original layout restored');
save70(storage,draft);assert.deepEqual(read70(storage),draft,'Approved configuration restored');
assert.equal(validate70({...draft,wood:99}),null);assert.equal(validate70({...draft,table:'outside'}),null);
data.set(DESIGN_KEY,'broken json');assert.deepEqual(read70(storage),initial70);
assert.throws(()=>save70({setItem:()=>{throw new Error('quota');}},draft));
console.log('PASS isolated floor, unchanged envelope, preview not saved, approval restored, invalid data and storage failure');
