import {useEffect,useState,lazy,Suspense} from 'react';
import type {FormEvent} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Box,Image,Clapperboard,Calculator,FileText,Receipt,Wallet,ArrowUpRight,ArrowRight,Plus,Search,ChevronRight,PanelLeftClose,PanelLeftOpen,Download,FolderOpen,Check,Clock,Settings2,X,Layers3,SlidersHorizontal} from 'lucide-react';
import {Dialog} from '../ui';
import './portal.css';
const Studio=lazy(()=>import('./SpatialStudio'));
const sections=[{id:'inicio',label:'Visão geral',icon:LayoutDashboard},{id:'projetos',label:'Projetos',icon:FolderOpen},{id:'estudio',label:'Estúdio 3D',icon:Box},{id:'imagens',label:'Imagens',icon:Image},{id:'videos',label:'Vídeos',icon:Clapperboard},{id:'orcamentos',label:'Orçamentos',icon:Calculator},{id:'contratos',label:'Contratos',icon:FileText},{id:'notas',label:'Notas e faturamento',icon:Receipt},{id:'financeiro',label:'Financeiro',icon:Wallet}];
const projects=[{name:'Torre M',kind:'Experiência navegável',img:'/assets/torre.webp',url:'/apresentar/m',status:'Experiência disponível'},{name:'G400',kind:'Arquitetura & interiores',img:'/assets/g400.webp',url:'/apresentar/g400',status:'Experiência disponível'},{name:'Moradas da Serra',kind:'Implantação & paisagem',img:'/assets/moradas.webp',url:'/apresentar/moradas-da-serra',status:'Experiência disponível'}];
type Entry={id:string;type:string;name:string;client:string;value:number;date:string;status:string;direction:string};
type Brief={id:string;type:string;name:string;prompt:string;format:string;reference:string};
const samples:Entry[]=[{id:'demo-1',type:'contratos',name:'Experiência residencial · exemplo',client:'Cliente demonstração A',value:18000,date:'2026-10-20',status:'Em revisão',direction:'Entrada'},{id:'demo-2',type:'contratos',name:'Interiores · exemplo',client:'Cliente demonstração B',value:8000,date:'2026-10-28',status:'Rascunho',direction:'Entrada'},{id:'demo-3',type:'financeiro',name:'Entrada de projeto · exemplo',client:'Cliente demonstração A',value:6000,date:'2026-10-12',status:'Previsto',direction:'Entrada'},{id:'demo-4',type:'financeiro',name:'Produção visual · exemplo',client:'Fornecedor demonstração',value:1200,date:'2026-10-15',status:'Previsto',direction:'Saída'}];
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function read<T>(key:string,fallback:T):T{try{const data=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(data)?data as T:fallback;}catch{return fallback;}}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function App(){
 const route=()=>location.pathname.split('/')[2]||'inicio';
 const [page,setPage]=useState(route),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState('');
 const [entries,setEntries]=useState<Entry[]>(()=>read('eme-spatial:management:v1',samples)),[briefs,setBriefs]=useState<Brief[]>(()=>read('eme-spatial:briefs:v1',[]));
 const [filter,setFilter]=useState('Todos'),[contract,setContract]=useState('demo-1'),[portion,setPortion]=useState(30),[tax,setTax]=useState(6);
 const selected=sections.find(s=>s.id===page);const title=selected?.label||'Configurações';
 function go(id:string){history.pushState({},'',id==='inicio'?'/portal':'/portal/'+id);setPage(id);setQuery('');setFilter('Todos');setMenu(false);window.scrollTo(0,0);}
 useEffect(()=>{const onPop=()=>{setPage(route());setQuery('');};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 useEffect(()=>{document.title=title+' · EME Spatial';},[title]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t);},[notice]);
 function persist<T>(key:string,value:T,update:()=>void){try{localStorage.setItem(key,JSON.stringify(value));update();setNotice('Rascunho salvo neste navegador.');return true;}catch{setNotice('Não foi possível salvar. O armazenamento do navegador está indisponível.');return false;}}
 function saveEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const value=Number(d.get('value'));if(!Number.isFinite(value)||value<0)return;const row:Entry={id:crypto.randomUUID(),type:modal,name:String(d.get('name')).trim(),client:String(d.get('client')).trim(),value,date:String(d.get('date')),status:'Rascunho',direction:String(d.get('direction')||'Entrada')};if(persist('eme-spatial:management:v1',[...entries,row],()=>setEntries([...entries,row])))setModal('');}
 function saveBrief(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const row:Brief={id:crypto.randomUUID(),type:page,name:String(data.get('name')).trim(),prompt:String(data.get('prompt')).trim(),format:String(data.get('format')),reference:String(data.get('reference'))};persist('eme-spatial:briefs:v1',[...briefs,row],()=>setBriefs([...briefs,row]));}
 const contracts=entries.filter(e=>e.type==='contratos'),financial=entries.filter(e=>e.type==='financeiro');
 const income=financial.filter(e=>e.direction==='Entrada').reduce((s,e)=>s+e.value,0),expense=financial.filter(e=>e.direction==='Saída').reduce((s,e)=>s+e.value,0);
 const picked=contracts.find(e=>e.id===contract)||contracts[0],invoice=(picked?.value||0)*portion/100;
 const visibleProjects=projects.filter(p=>(p.name+' '+p.kind).toLowerCase().includes(query.toLowerCase()));
 const metrics=[['Contratos em planejamento',money(contracts.reduce((s,e)=>s+e.value,0)),'Valores demonstrativos',FileText],['Entradas previstas',money(income),'Fluxo demonstrativo',ArrowUpRight],['Saídas previstas',money(expense),'Custos demonstrativos',Wallet],['Saldo previsto',money(income-expense),'Entradas menos saídas',Layers3]] as const;
 const projectCards=<div className="project-grid">{visibleProjects.map((p,i)=><a className="project-card" key={p.name} href={p.url} target="_blank" rel="noreferrer"><div className="project-photo"><img src={p.img} alt={p.name}/><span className="image-tag">{i===0?'3D NAVEGÁVEL':i===1?'INTERIORES':'EMPREENDIMENTO'}</span><span className="round-arrow"><ArrowUpRight size={19}/></span></div><div className="project-details"><small>{p.kind}</small><h3>{p.name}</h3><div><span className="dot"/>{p.status}</div></div></a>)}{!visibleProjects.length&&<p>Nenhum projeto encontrado.</p>}</div>;
 return <div className="workspace select-portal"><a className="skip-link" href="#main">Pular para o conteúdo</a>{menu&&<button aria-label="Fechar menu" className="scrim" onClick={()=>setMenu(false)}/>}
 <aside className={menu?'sidebar open':'sidebar'}><a href="/" className="brand"><img src="/assets/simbolo.webp" alt=""/><span>EME <b>SPATIAL</b><small>CREATIVE WORKSPACE</small></span></a><div className="workspace-label"><span className="workspace-icon">M</span><div>Meu workspace<small>Estúdio pessoal</small></div><ChevronRight size={15}/></div><p className="nav-label">WORKSPACE</p><nav aria-label="Portal">{sections.map((s,i)=><div key={s.id}>{i===5&&<p className="nav-label">GESTÃO</p>}<button onClick={()=>go(s.id)} className={page===s.id?'nav-item active':'nav-item'} aria-current={page===s.id?'page':undefined}><s.icon size={18} strokeWidth={1.65}/>{s.label}{s.id==='estudio'&&<span className="tiny-badge">3D</span>}</button></div>)}</nav><div className="sidebar-bottom"><div className="local-card"><span className="dot"/>Prévia do portal<p>Seu próximo espaço de criação.</p><small>Rascunhos salvos neste navegador.</small></div><button className="nav-item" onClick={()=>go('configuracoes')}><Settings2 size={18}/>Configurações</button><div className="profile"><span>MF</span><div>Mateus Forest<small>Workspace pessoal</small></div><button aria-label="Recolher menu" className="mobile-only" onClick={()=>setMenu(false)}><PanelLeftClose size={18}/></button></div></div></aside>
 <div className="workspace-body"><header className="topbar"><div className="breadcrumb"><button className="mobile-only" aria-label="Abrir menu" onClick={()=>setMenu(true)}><PanelLeftOpen size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="top-actions"><span className="preview-pill"><span className="dot"/>Modo demonstração</span><a href="/" target="_blank" rel="noreferrer">Ver site <ArrowUpRight size={15}/></a><span className="avatar">MF</span></div></header>
 <main id="main"><div className="page-heading"><div><p className="eyebrow">EME SPATIAL / {page==='inicio'?'SEU ESTÚDIO, EM UM SÓ LUGAR':'WORKSPACE'}</p><h1>{page==='inicio'?'Boas ideias merecem espaço.':title}</h1><p>{page==='inicio'?'Crie experiências. Organize projetos. Cuide do seu negócio.':page==='estudio'?'Do briefing ao ambiente navegável, com as ferramentas do seu estúdio.':page==='orcamentos'?'Defina escopo, esforço e investimento para a próxima entrega.':'Tudo o que você precisa para dar o próximo passo.'}</p></div><button className="primary" onClick={()=>page==='contratos'||page==='financeiro'?setModal(page):go('estudio')}><Plus size={17}/>{page==='contratos'?'Novo contrato':page==='financeiro'?'Novo lançamento':'Novo projeto'}</button></div>
 <div className="demo-note"><span className="note-icon">i</span>Prévia visual com dados de exemplo. Sem autenticação ou serviços conectados; use somente dados de teste.</div>
 {page==='inicio'&&<><section className="hero-panel"><img src="/assets/interior.webp" alt="Ambiente de interiores usado como referência visual"/><div className="hero-shade"/><div className="hero-content"><span className="hero-kicker"><Box size={14}/> SPATIAL STUDIO</span><h2>Da sua visão.<br/>Para uma nova realidade.</h2><p>Arquitetura, luz e movimento.<br/>O próximo projeto começa aqui.</p><button onClick={()=>go('estudio')}>Abrir estúdio 3D <ArrowUpRight size={18}/></button></div><div className="hero-caption"><span className="dot"/>ARQUITETURA & EXPERIÊNCIAS IMERSIVAS</div></section><div className="metrics">{metrics.map(([label,value,note,Icon])=><article key={label}><div><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{note}</small></article>)}</div><div className="section-head"><div><h2>Seus projetos, novas perspectivas.</h2><p>Experiências existentes no EME Spatial.</p></div><button className="text-button" onClick={()=>go('projetos')}>Ver projetos <ArrowRight size={16}/></button></div>{projectCards}<div className="bottom-grid"><section className="panel"><div className="section-head"><h2>Do conceito à entrega</h2><span className="badge">Seu fluxo</span></div>{[['01','Defina a experiência','Briefing, referências e direção visual.','estudio'],['02','Planeje o investimento','Escopo, custos e proposta comercial.','orcamentos'],['03','Organize a operação','Contratos e acompanhamento financeiro.','contratos']].map(([n,t,d,id])=><button className="workflow" key={n} onClick={()=>go(id)}><span>{n}</span><div><strong>{t}</strong><small>{d}</small></div><ArrowUpRight size={17}/></button>)}</section><section className="panel creation-panel"><span className="eyebrow">EXPLORE AS POSSIBILIDADES</span><h2>Um estúdio.<br/>Muitas formas de criar.</h2><p>Prepare referências e briefings para as próximas imagens e vídeos.</p><div><button className="secondary" onClick={()=>go('imagens')}><Image size={16}/>Criar imagem</button><button className="secondary" onClick={()=>go('videos')}><Clapperboard size={16}/>Criar vídeo</button></div></section></div></>}
 {page==='projetos'&&<><div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Buscar projetos" placeholder="Buscar projetos..." value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="muted">{visibleProjects.length} experiências</span></div>{projectCards}<section className="panel spaced"><h2>Oficina de criação</h2><p>Crie e salve novos rascunhos, ajuste o orçamento e monte uma composição usando a base G400.</p><button className="primary" onClick={()=>go('estudio')}>Abrir meus rascunhos <ArrowRight size={16}/></button></section></>}
 {(page==='estudio'||page==='orcamentos')&&<Suspense fallback={<div className="panel">Carregando ferramentas do estúdio…</div>}><Studio key={page} initialTab={page==='orcamentos'?'estimate':'project'}/></Suspense>}
 {(page==='imagens'||page==='videos')&&<><div className="creative-layout"><form className="panel brief-form" onSubmit={saveBrief}><span className="eyebrow">{page==='imagens'?'IMAGE':'MOTION'} STUDIO</span><h2>{page==='imagens'?'Imagine a próxima perspectiva.':'Dê movimento à sua visão.'}</h2><label>Nome da criação<input required name="name" maxLength={120} placeholder="Ex.: Sala de estar ao entardecer"/></label><label>Direção criativa<textarea name="prompt" required rows={6} maxLength={3000} placeholder="Descreva o ambiente, a iluminação, os materiais e a sensação que quer transmitir..."/></label><div className="form-columns"><label>Formato<select name="format"><option>Horizontal · 16:9</option><option>Vertical · 9:16</option><option>Quadrado · 1:1</option></select></label><label>Referência<select name="reference"><option>Interiores</option><option>Arquitetura exterior</option><option>Paisagismo</option></select></label></div><button className="primary" type="submit"><Check size={16}/>Salvar briefing</button><p className="fine">A geração será conectada em uma próxima etapa. Aqui você pode preparar e salvar seus briefings.</p></form><div className="creative-preview"><img src={page==='imagens'?'/assets/contemporanea.webp':'/assets/interior.webp'} alt="Referência visual de arquitetura"/><span className="image-tag">REFERÊNCIA VISUAL · NÃO GERADA AGORA</span><div><span className="hero-kicker">{page==='imagens'?'LUZ, MATÉRIA E ATMOSFERA':'PERCURSO, RITMO E PERSPECTIVA'}</span><h2>{page==='imagens'?'Cada detalhe conta uma história.':'Espaços que ganham vida.'}</h2></div></div></div><div className="section-head"><h2>Briefings salvos</h2><span className="badge">Neste navegador</span></div><div className="brief-grid">{briefs.filter(b=>b.type===page).map(b=><article className="panel" key={b.id}><span className="badge">{b.format}</span><h3>{b.name}</h3><p>{b.prompt}</p><button className="text-button" onClick={()=>download(b,'briefing-spatial.json')}><Download size={15}/>Exportar briefing</button></article>)}{!briefs.some(b=>b.type===page)&&<div className="empty-state"><Layers3 size={28}/><h3>O primeiro conceito começa com uma ideia.</h3><p>Preencha o briefing acima para organizar sua próxima criação.</p></div>}</div>{page==='videos'&&<a className="panel video-link" href="/apresentar/m" target="_blank" rel="noreferrer"><Clapperboard/><div><h3>Estúdio de vídeo drone</h3><p>Abra a experiência Torre M para explorar a ferramenta de vídeo já existente.</p></div><ArrowUpRight/></a>}</>}
 {(page==='contratos'||page==='financeiro')&&<>{page==='financeiro'&&<div className="metrics three">{[['Entradas previstas',income],['Saídas previstas',expense],['Saldo previsto',income-expense]].map(([t,v])=><article key={t}><small>{t}</small><strong>{money(Number(v))}</strong><small>Simulação · dados de teste</small></article>)}</div>}<section className="panel"><div className="toolbar"><label className="search"><Search size={17}/><input placeholder="Buscar por nome ou cliente..." aria-label="Buscar registros" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="filter"><SlidersHorizontal size={15}/><select aria-label="Filtrar status" value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Rascunho</option><option>Em revisão</option><option>Previsto</option></select></label><button className="secondary" onClick={()=>download(entries.filter(e=>e.type===page),'spatial-'+page+'.json')}><Download size={16}/>Exportar</button></div><div className="table-scroll"><table><thead><tr><th>{page==='contratos'?'Contrato / cliente':'Lançamento / contato'}</th><th>Data prevista</th><th>Valor</th><th>Status</th><th/></tr></thead><tbody>{entries.filter(e=>e.type===page&&(filter==='Todos'||e.status===filter)&&(e.name+' '+e.client).toLowerCase().includes(query.toLowerCase())).map(e=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.client}</small></td><td>{e.date?new Date(e.date+'T12:00:00').toLocaleDateString('pt-BR'):'A definir'}</td><td><strong>{page==='financeiro'&&e.direction==='Saída'?'− ':''}{money(e.value)}</strong><small>{page==='financeiro'?e.direction:'Valor do contrato'}</small></td><td><span className="status"><Clock size={12}/>{e.status}</span></td><td><button className="icon-button" aria-label={'Ver '+e.name} onClick={()=>setModal(e.id)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{!entries.some(e=>e.type===page&&(filter==='Todos'||e.status===filter)&&(e.name+' '+e.client).toLowerCase().includes(query.toLowerCase()))&&<p className="empty-state">Nenhum registro encontrado.</p>}</div></section><p className="fine spaced">{page==='contratos'?'Organização visual dos contratos. Assinaturas e documentos jurídicos ainda não estão conectados.':'Lançamentos demonstrativos, sem integração bancária ou conciliação.'}</p></>}
 {page==='notas'&&<div className="invoice-layout"><section className="panel brief-form"><span className="eyebrow">PLANEJAMENTO DE FATURAMENTO</span><h2>Do contrato à parcela.</h2><p>Simule o valor a faturar e uma reserva para tributos.</p><label>Contrato<select value={picked?.id||''} onChange={e=>setContract(e.target.value)}>{contracts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Parcela do contrato (%)<input type="number" min={0} max={100} value={portion} onChange={e=>setPortion(Math.max(0,Math.min(100,Number(e.target.value))))}/></label><label>Alíquota estimada informada por você (%)<input type="number" min={0} max={100} step={0.1} value={tax} onChange={e=>setTax(Math.max(0,Math.min(100,Number(e.target.value))))}/></label><p className="fine">O percentual é apenas uma premissa de simulação. Não há cálculo fiscal validado nem emissão de NFS-e nesta versão.</p><button className="primary" onClick={()=>download({status:'simulacao',contract:picked,portion,invoice,estimatedRate:tax,reserve:invoice*tax/100},'simulacao-faturamento.json')}><Download size={16}/>Exportar simulação</button></section><section className="invoice-summary"><Receipt size={29} strokeWidth={1.4}/><span className="eyebrow">VALOR BRUTO A FATURAR</span><strong>{money(invoice)}</strong><p>{portion}% de {money(picked?.value||0)}</p><hr/><div><span>Reserva estimada ({tax}%)</span><b>{money(invoice*tax/100)}</b></div><div><span>Valor após reserva</span><b>{money(invoice*(1-tax/100))}</b></div><small>Simulação de reserva. Não representa retenção ou valor líquido de uma nota emitida.</small><span className="badge">Emissão fiscal não conectada</span></section></div>}
 {page==='configuracoes'&&<section className="panel brief-form"><span className="eyebrow">MEU WORKSPACE</span><h2>Um espaço dedicado ao EME Spatial.</h2><label>Endereço do portal<input readOnly value="www.emespatial.com/portal"/></label><label>Armazenamento<input readOnly value="Rascunhos locais · este navegador"/></label><p>Esta prévia não tem autenticação. Os rascunhos não são sincronizados entre dispositivos. Use dados de teste e exporte os arquivos que deseja manter.</p><button className="secondary" onClick={()=>download({entries,briefs,studio:read('eme-spatial:studio:v1',[])},'workspace-spatial-backup.json')}><Download size={16}/>Exportar rascunhos</button><div className="integration-list">{['Autenticação e acesso privado','Geração de imagens e vídeos','Assinatura de contratos','Emissão de notas fiscais'].map(i=><div key={i}><span>{i}</span><span className="badge">Próxima etapa</span></div>)}</div></section>}
 <footer className="portal-footer"><span>EME SPATIAL <b>WORKSPACE</b></span><span>Mais espaço para criar.</span></footer></main></div>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {modal&&<Dialog title={modal==='contratos'?'Novo contrato · rascunho':modal==='financeiro'?'Novo lançamento · rascunho':'Detalhes do registro'} onClose={()=>setModal('')}>{['contratos','financeiro'].includes(modal)?<form className="brief-form" onSubmit={saveEntry}><p className="fine">Use dados de teste. Este registro fica salvo somente neste navegador.</p><label>Nome<input name="name" required maxLength={120}/></label><label>Cliente ou contato<input name="client" required maxLength={120}/></label><div className="form-columns"><label>Valor (R$)<input name="value" type="number" min={0} max={100000000} step="0.01" required/></label><label>Data prevista<input name="date" type="date" required/></label></div>{modal==='financeiro'&&<label>Tipo<select name="direction"><option>Entrada</option><option>Saída</option></select></label>}<button className="primary" type="submit"><Check size={16}/>Salvar rascunho</button></form>:<>{entries.filter(e=>e.id===modal).map(e=><div className="record-detail" key={e.id}><span className="badge">{e.status}</span><h2>{e.name}</h2><p>{e.client}</p><strong>{money(e.value)}</strong><p>Data prevista: {e.date}</p><p className="fine">Registro demonstrativo, sem assinatura ou movimentação financeira.</p><button className="secondary" onClick={()=>download(e,'registro-spatial.json')}><Download size={16}/>Exportar registro</button></div>)}</>}</Dialog>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
