import {useEffect,useState} from 'react';
import {production73} from '../developments/mProduction73';
import {decode74,download74,import74,list74,package74,save74} from './production74';
import type {Media74} from './production74';
import './production74.css';
type Request74={schema_version:string;id:string;projectId:string;projectName:string;unit:string;sourceSha256:string;design:unknown;mode:string;validationId:string|null};
const queueKey='eme-spatial:production-requests:v74';
function requests():Request74[]{try{const v=JSON.parse(localStorage.getItem(queueKey)||'[]');return Array.isArray(v)?v:[];}catch{return [];}}
function Preview({row}:{row:Media74}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(row.blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[row.blob]);return row.kind==='video'?<video src={url} controls preload="none"/>:<img src={url} alt={row.name} loading="lazy"/>;}
export default function ProductionStudio74(){
 const [rows,setRows]=useState<Media74[]>([]),[queue,setQueue]=useState(requests),[mode,setMode]=useState('validation'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[project,setProject]=useState('all');
 const refresh=async()=>setRows((await list74()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));
 useEffect(()=>{refresh().catch(()=>setNotice('Não foi possível abrir a biblioteca local.'));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(false);}}
 async function makeRequest(){
  const response=await fetch('/assets/production74-source.json');if(!response.ok)throw Error('Base de produção indisponível.');const source=await response.json();const saved=production73(localStorage);
  if(Object.entries(saved.design).some(([k,v])=>source.design[k]!==v))throw Error('Os acabamentos salvos mudaram. Exporte a versão aprovada do apartamento e sincronize o Blender antes de produzir.');
  const validation=rows.find(r=>r.origin.projectId==='m-14'&&r.origin.mode==='validation'&&r.approvedAt&&r.origin.sourceSha256===source.sourceSha256);
  if(mode==='final'&&!validation)throw Error('Importe e aprove primeiro uma validação Cycles desta versão. A MF também verifica a aprovação local.');
  const req:Request74={schema_version:'eme-spatial-job/1',id:crypto.randomUUID(),projectId:'m-14',projectName:'Torre M · Apartamento 14',unit:'m-14',sourceSha256:source.sourceSha256,design:saved.design,mode,validationId:validation?.id||null};
  const next=[req,...queue];localStorage.setItem(queueKey,JSON.stringify(next));setQueue(next);download74(new Blob([JSON.stringify(req,null,2)],{type:'application/json'}),'Spatial-pedido-'+req.id+'.json');setNotice('Pedido preparado. Abra Produção Spatial na MF e importe esse arquivo para iniciar.');
 }
 const visible=rows.filter(r=>project==='all'||r.origin.projectId===project);
 const projects=Array.from(new Map(rows.map(r=>[r.origin.projectId,r.origin.projectName])).entries());
 return <div className="production74"><section className="panel production74-intro"><div><span className="eyebrow">BLENDER + MF VIDEO IA</span><h2>O mesmo projeto.<br/>Novas formas de apresentar.</h2><p>Produza imagens e percursos a partir do pavimento completo do apartamento 14. Organize também imagens, vídeos e montagens criados na MF sem modelo 3D.</p></div><ol><li><b>Prepare o pedido</b><span>Versão salva, câmera e tipo de produção.</span></li><li><b>Renderize na MF</b><span>O computador processa; o cenário web continua leve.</span></li><li><b>Revise e aprove</b><span>Importe os resultados e prepare a entrega.</span></li></ol></section>
 <div className="production74-controls"><section className="panel brief-form"><h3>Produção do apartamento 14</h3><label>Etapa<select value={mode} onChange={e=>setMode(e.target.value)}><option value="validation">Validação · uma imagem em Cycles</option><option value="preview">Prévia · três vistas + percurso em Eevee</option><option value="final">Final · três vistas + percurso em Cycles</option></select></label><p className="fine">Living, cozinha e sacada. Percurso lateral contínuo de 6 segundos no living. A produção final depende da aprovação da validação.</p><button className="primary" disabled={busy} onClick={()=>run(makeRequest)}>Preparar pedido para a MF</button><a href="http://127.0.0.1:7860/spatial" target="_blank" rel="noopener noreferrer">Abrir produção local na MF ↗</a><small>A MF precisa estar aberta neste computador. A troca é feita por arquivos; o site não executa renderização na nuvem.</small></section>
 <section className="panel brief-form"><h3>Receber resultados</h3><p>Exporte um resultado ou uma tarefa completa na MF e importe o pacote aqui. Cada arquivo mantém projeto, origem, versão e integridade.</p><label className="secondary">Importar pacote da MF<input type="file" accept="application/json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)void run(async()=>{if(f.size>115*1024*1024)throw Error('Exporte cada resultado separadamente.');const items=await decode74(await f.text());await import74(items);await refresh();setNotice('Resultados importados. Revise e aprove cada versão para preparar a entrega.');});}}/></label><p className="fine">Biblioteca privada deste navegador. Exporte uma cópia para preservar os arquivos ou transferir para outro dispositivo. Importar não publica mídia no site.</p><button className="secondary" disabled={busy||!rows.length} onClick={()=>run(async()=>download74(await package74(rows),'Spatial-biblioteca-backup.json'))}>Exportar biblioteca</button></section></div>
 {notice&&<p role="status" className="production74-notice">{notice}</p>}
 {queue.length>0&&<section className="panel"><h3>Pedidos e resultados</h3><p className="fine">O andamento em tempo real aparece na MF. Aqui, o pedido é concluído quando você importa o resultado.</p>{queue.map(q=><div className="production74-request" key={q.id}><span>{q.projectName} · {q.mode==='validation'?'Validação Cycles':q.mode==='preview'?'Prévia Eevee':'Final Cycles'}<small>{rows.some(r=>r.origin.id===q.id)?'Resultado importado':'Pedido preparado · aguarda resultado'}</small></span><button className="secondary" onClick={()=>download74(new Blob([JSON.stringify(q)],{type:'application/json'}),'Spatial-pedido-'+q.id+'.json')}>Baixar pedido</button></div>)}</section>}
 <div className="section-head"><h2>Biblioteca de produção</h2><select aria-label="Filtrar projeto" value={project} onChange={e=>setProject(e.target.value)}><option value="all">Todos os projetos</option>{projects.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></div>
 <div className="production74-library">{visible.map(r=><article className="panel" key={r.id}><Preview row={r}/><small>{r.origin.projectName} · {r.origin.engine}</small><h3>{r.name}</h3><p>{r.approvedAt?'Aprovado para entrega':'Em revisão'} · {new Date(r.createdAt).toLocaleDateString('pt-BR')}</p><details><summary>Origem desta versão</summary><p>{r.origin.originType==='blender'?'Pavimento sincronizado no Blender':r.origin.originType==='cinematic-edit'?'Montagem na MF a partir de arquivos do projeto':'Arquivo vinculado na MF'}</p><small>Versão {r.id}<br/>SHA-256 {r.sha256}</small></details><div className="production74-buttons"><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await save74([{...r,approvedAt:r.approvedAt?null:new Date().toISOString()}]);await refresh();})}>{r.approvedAt?'Voltar à revisão':'Aprovar versão'}</button><button className="secondary" onClick={()=>download74(r.blob,r.name.replace(/[^\p{L}\p{N} -]/gu,'')+(r.kind==='video'?'.mp4':r.mime==='image/png'?'.png':r.mime==='image/webp'?'.webp':'.jpg'))}>Baixar arquivo</button><button className="secondary" disabled={busy} onClick={()=>run(async()=>download74(await package74([r]),"Spatial-versao-"+r.id+".json"))}>Backup desta versão</button></div></article>)}</div>
 {!visible.length&&<div className="empty-state"><h3>Seus resultados aparecerão aqui.</h3><p>Importe o primeiro pacote exportado pela MF Video IA.</p></div>}
 <button className="primary" disabled={busy||!visible.some(r=>r.approvedAt)} onClick={()=>run(async()=>{download74(await package74(visible.filter(r=>r.approvedAt),true),'Spatial-entrega-aprovada.json');setNotice('Pacote de entrega exportado somente com as versões aprovadas.');})}>Exportar entrega aprovada</button>
 </div>;
}
