import {useEffect,useRef,useState} from 'react';
import type {DroneState56,DroneStudio56} from './mDroneStudio56';
import {DRONE_STORAGE56,validRoute56,droneDimensions56,pointAngles57,type DroneRoute56} from './mDronePath56';
import './m-drone56.css';

export default function MDronePanel56({state,studio}:{state:DroneState56;studio:DroneStudio56}){
 const [saved,setSaved]=useState<DroneRoute56[]>([]),[notice,setNotice]=useState(''),file=useRef<HTMLInputElement>(null);
 const [orbitRadius,setOrbitRadius]=useState(65),[orbitHeight,setOrbitHeight]=useState(55);
 const [collapsed,setCollapsed]=useState(false);
 const [clips,setClips]=useState<{id:string;name:string;url:string;downloadUrl:string;filename:string}[]>([]),[watch,setWatch]=useState<string|null>(null);
 useEffect(()=>{let active=true;fetch('/api/spatial-local/videos').then(r=>r.ok?r.json():null).then(data=>{if(active&&Array.isArray(data?.videos))setClips(data.videos);}).catch(()=>{});return()=>{active=false;};},[state.result?.url]);
 useEffect(()=>{try{const raw=localStorage.getItem(DRONE_STORAGE56);if(raw){const list=JSON.parse(raw);if(!Array.isArray(list))throw new Error();setSaved(list.slice(0,50).map(validRoute56));}}catch{setNotice('Não foi possível ler os voos salvos. Seus novos trajetos ainda podem ser exportados.');}},[]);
 const busy=state.phase!=='edit',recording=['record','record-pause','finishing'].includes(state.phase),paused=state.phase==='pause'||state.phase==='record-pause';
 const route=state.route,selected=route.points[state.selected],[width,height]=droneDimensions56(route);
 const angles=selected?pointAngles57(selected):{yaw:0,pitch:0};
 const mapView=()=>{setCollapsed(true);requestAnimationFrame(()=>studio.mapView());};
 function save(){try{const list=[validRoute56(route),...saved.filter(r=>r.id!==route.id)];if(list.length>50)throw new Error('Limite de trajetos locais.');localStorage.setItem(DRONE_STORAGE56,JSON.stringify(list));setSaved(list);setNotice('Trajeto salvo neste navegador.');}catch{setNotice('O armazenamento está indisponível ou cheio. Use “Exportar trajeto” para guardar uma cópia.');}}
 function exportRoute(){const url=URL.createObjectURL(new Blob([JSON.stringify(route,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='eme-trajeto-'+route.id.slice(0,8)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function importRoute(input:HTMLInputElement){try{const f=input.files?.[0];if(!f)return;if(f.size>200000)throw new Error('Arquivo grande demais para um trajeto.');const route=validRoute56(JSON.parse(await f.text()));studio.load(route);setNotice('Trajeto importado. Salve para mantê-lo neste navegador.');}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível importar o trajeto.');}input.value='';}
 return <>{!busy&&<nav className="drone57-nav" aria-label="Mover a vista de edição">
  <div><button onClick={mapView}>Mapa da rota</button><button aria-pressed={state.editorMode==='orbit'} onClick={()=>studio.editorMode('orbit')}>Orbitar</button><button aria-pressed={state.editorMode==='pan'} onClick={()=>studio.editorMode('pan')}>Deslocar</button><button aria-pressed={state.editorMode==='pilot'} onClick={()=>studio.editorMode('pilot')}>Pilotar câmera</button></div>
  <div><button aria-label="Subir câmera" onClick={()=>studio.moveView(0,5,0)}>↑ Subir</button><button aria-label="Descer câmera" onClick={()=>studio.moveView(0,-5,0)}>↓ Descer</button><button aria-label="Mover câmera à esquerda" onClick={()=>studio.moveView(-5,0,0)}>←</button><button aria-label="Mover câmera à direita" onClick={()=>studio.moveView(5,0,0)}>→</button><button onClick={()=>studio.moveView(0,0,5)}>Avançar</button><button onClick={()=>studio.moveView(0,0,-5)}>Recuar</button></div>
  <div><button aria-expanded={!collapsed} onClick={()=>setCollapsed(!collapsed)}>{collapsed?'Mostrar ajustes':'Recolher painel'}</button>{collapsed&&<><button aria-pressed={state.marking} onClick={()=>studio.marking()}>{state.marking?'Marcando pontos ✓':'Marcar pontos'}</button><button disabled={route.points.length<2} onClick={()=>void studio.start()}>▶ Prévia</button></>}</div>
  <span>{state.editorMode==='pilot'?'Arraste para olhar · roda para avançar':state.editorMode==='pan'?'Arraste para deslocar, inclusive na vertical':'Arraste para girar · botão direito para deslocar'} · WASD move · Q/E desce/sobe</span>
 </nav>}<aside className="m-drone56" hidden={collapsed&&!busy} aria-label="Estúdio de vídeo drone" data-testid="drone-studio">
  <div className="drone56-head"><div><span>EME · FILMES DO EMPREENDIMENTO</span><h2>Estúdio de voo</h2></div><button aria-label="Fechar estúdio de voo" onClick={()=>studio.close()}>×</button></div>
  {busy?<div className="drone56-flight">
   <div className="drone56-live"><i className={recording?'record':''}/>{recording?'Gravando seu vídeo':'Prévia do voo'}<span>{Math.round(state.progress*route.duration)} / {route.duration}s</span></div>
   <input type="range" min="0" max="1000" value={Math.round(state.progress*1000)} disabled={recording||state.phase==='preparing'} aria-label="Posição no voo" onChange={e=>studio.seek(Number(e.target.value)/1000)}/>
   <div className="drone56-row"><button disabled={state.phase==='preparing'||state.phase==='finishing'} onClick={()=>studio.pause()}>{paused?'Continuar':'Pausar'}</button><button onClick={()=>studio.stop(recording?'Gravação cancelada.':'')}>{recording?'Cancelar gravação':'Voltar à edição'}</button></div>
   <p>O vídeo mostra somente a cena, sem os menus e sem os pontos do trajeto.</p>
  </div>:<>
   <label>Nome do voo<input value={route.name} maxLength={80} onChange={e=>studio.patch({name:e.target.value})} placeholder="Ex.: Chegada ao M"/></label>
   <div className="drone56-section"><span className="drone56-step">01 · DESENHE SEU CAMINHO</span>
    <div className="drone56-row"><button className={state.marking?'active':''} aria-pressed={state.marking} onClick={()=>studio.marking()}>{state.marking?'Marcando pontos ✓':'Marcar na cena'}</button><button onClick={()=>studio.addView()}>Guardar vista atual</button></div>
    <p>{state.marking?'Clique para acrescentar pontos. Arraste uma bolinha para reposicioná-la.':'Use o mapa para desenhar, ou pilote a câmera e guarde cada enquadramento.'}</p>
    <div className="drone56-row"><label>Altura dos novos pontos · m<input type="number" min="-2.7" max="350" step=".5" value={state.height} onChange={e=>studio.height(Number(e.target.value))}/></label><label>Torre de referência<select aria-label="Torre de referência" value={state.focus} onChange={e=>studio.focus(e.target.value as 'm'|'b')}><option value="m">Torre M</option></select></label></div>
    <div className="drone56-points" aria-label="Pontos do trajeto">{route.points.length?route.points.map((p,i)=><button key={p.id} className={i===state.selected?'selected':''} aria-pressed={i===state.selected} aria-label={`Selecionar ponto ${i+1}`} onClick={()=>studio.select(i)}>{String(i+1).padStart(2,'0')}</button>):<span>Seu primeiro ponto começa aqui.</span>}</div>
    {selected&&<div className="drone56-selected"><div className="drone56-row"><label>Ponto {state.selected+1} · altura (m)<input aria-label="Altura do ponto selecionado" type="number" min="-2.7" max="350" step=".5" value={Number(selected.eye[1].toFixed(1))} onChange={e=>studio.pointHeight(state.selected,Number(e.target.value))}/></label><button className={state.through?'active':''} onClick={()=>void studio.viewPoint()}>Ver pela câmera</button></div>
     <label>Direção da câmera <span>{Math.round(angles.yaw)}°</span><input aria-label="Direção da câmera" type="range" min="-180" max="180" step="1" value={Math.round(angles.yaw)} onChange={e=>studio.angles({yaw:Number(e.target.value)})}/></label>
     <label>Inclinação <span>{Math.round(angles.pitch)}°</span><input aria-label="Inclinação da câmera" type="range" min="-85" max="85" step="1" value={Math.round(angles.pitch)} onChange={e=>studio.angles({pitch:Number(e.target.value)})}/></label>
     <label>Abertura da lente <span>{Math.round(selected.fov)}°</span><input aria-label="Abertura da lente" type="range" min="20" max="95" step="1" value={Math.round(selected.fov)} onChange={e=>studio.angles({fov:Number(e.target.value)})}/></label>
     <div className="drone56-row"><button onClick={()=>studio.aimTower()}>Mirar na torre</button><button aria-pressed={state.aiming} onClick={()=>studio.aiming()}>{state.aiming?'Clique no alvo…':'Escolher alvo na cena'}</button></div>
     <div className="drone56-row"><button disabled={state.selected===0} aria-label="Antecipar ponto" onClick={()=>studio.changePoint(state.selected,'up')}>←</button><button disabled={state.selected===route.points.length-1} aria-label="Adiar ponto" onClick={()=>studio.changePoint(state.selected,'down')}>→</button><button onClick={()=>studio.changePoint(state.selected,'replace')}>Aplicar esta vista</button><button aria-label="Remover ponto selecionado" onClick={()=>studio.changePoint(state.selected,'remove')}>Remover</button></div>
     <p>{state.through?'Você está olhando pelo ponto selecionado. Os ajustes acima já alteram esse ponto. Após pilotar manualmente, use “Aplicar esta vista”.':'Arraste a bolinha no mapa. A linha verde indica para onde a câmera olha.'}</p>
    </div>}
    <details><summary>Começar com um movimento pronto</summary><p>Crie uma volta contínua ao redor da torre de referência.</p><div className="drone56-row"><label>Raio da volta · m<input type="number" min="35" max="300" value={orbitRadius} onChange={e=>setOrbitRadius(Number(e.target.value))}/></label><label>Altura da volta · m<input type="number" min="5" max="250" value={orbitHeight} onChange={e=>setOrbitHeight(Number(e.target.value))}/></label></div><button className="drone57-orbit" onClick={()=>studio.orbit(orbitRadius,orbitHeight)}>Criar volta completa · 360°</button><div className="drone56-row"><button onClick={()=>studio.preset()}>Afastamento · Pullback</button><button onClick={()=>studio.preset(true)}>Aproximação · Zoom</button></div></details>
   </div>
   <div className="drone56-section"><span className="drone56-step">02 · DÊ RITMO AO VOO</span>
    <div className="drone56-row"><label>Movimento<select value={route.motion} onChange={e=>studio.patch({motion:e.target.value as DroneRoute56['motion']})}><option value="smooth">Cinemático suave</option><option value="fpv">FPV · inclinação leve</option></select></label><label>Duração<select value={route.duration} onChange={e=>studio.patch({duration:Number(e.target.value)})}>{[6,10,15,20,30,45,60,90].map(n=><option key={n} value={n}>{n} segundos</option>)}</select></label></div>
    <div className="drone56-row"><label>Formato<select value={route.format} onChange={e=>studio.patch({format:e.target.value as DroneRoute56['format']})}><option value="landscape">Horizontal · 16:9</option><option value="portrait">Vertical · 9:16</option><option value="square">Quadrado · 1:1</option></select></label><label>Qualidade<select value={route.quality} onChange={e=>studio.patch({quality:e.target.value as DroneRoute56['quality']})}><option value="hd">HD · mais leve</option><option value="fullhd">Full HD</option></select></label></div>
    <label>Luz do voo <span>{route.dayTime<50?'Dia':route.dayTime<78?'Entardecer':'Noite'}</span><input type="range" min="0" max="100" value={route.dayTime} aria-label="Luz do voo" onChange={e=>studio.patch({dayTime:Number(e.target.value)})}/></label>
    <p>Voo contínuo, sem parar nos pontos. A curva dourada mostra o caminho real; confira a prévia para contornar obstáculos.</p>
   </div>
   <div className="drone56-actions"><button className="primary" disabled={route.points.length<2} onClick={()=>void studio.start()}>▶ Play · prévia</button><button disabled={route.points.length<2||!state.codec} onClick={()=>void studio.start(true)}>Gerar vídeo {state.codec}</button></div>
   <p className="drone56-meta">{width} × {height} · sem áudio · vídeo da própria cena 3D{state.codec==='WebM'?' · este navegador exporta WebM':''}</p>
   {!state.codec&&<p role="status">A gravação não está disponível neste navegador. Você pode salvar e exportar o trajeto.</p>}
   {state.result&&<div className="drone56-result"><video controls playsInline preload="metadata" src={state.result.url} aria-label="Vídeo do voo gerado"/><a className="primary" href={state.result.downloadUrl??state.result.url} download={state.result.filename}>Baixar vídeo · {(state.result.bytes/1048576).toFixed(1)} MB ↓</a></div>}
   <div className="drone56-section"><span className="drone56-step">03 · GUARDE PARA DEPOIS</span><div className="drone56-row"><button disabled={route.points.length<2} onClick={save}>Salvar trajeto</button><button onClick={()=>{studio.fresh();setNotice('');}}>Novo voo</button></div>
    {saved.length>0&&<div className="drone56-library">{saved.map(r=><button key={r.id} onClick={()=>{studio.load(r);setNotice('Trajeto carregado. Use Play para assistir.');}}><span>{r.name||'Voo sem título'}</span><small>{r.points.length} pontos · {r.duration}s ↗</small></button>)}</div>}
    <details><summary>Levar o trajeto para outro computador</summary><div className="drone56-row"><button disabled={!route.points.length} onClick={exportRoute}>Exportar trajeto</button><button onClick={()=>file.current?.click()}>Importar trajeto</button></div><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>void importRoute(e.currentTarget)}/></details>
    {clips.length>0&&<details><summary>Vídeos salvos neste PC · {clips.length}</summary><div className="drone56-library">{clips.map(c=><div key={c.id} className="drone56-clip"><button onClick={()=>setWatch(watch===c.url?null:c.url)}>{c.name||'Voo EME'} · assistir</button><a href={c.downloadUrl} download={c.filename} aria-label={`Baixar ${c.name}`}>↓</a></div>)}</div>{watch&&<video className="drone56-saved-video" src={watch} controls playsInline aria-label="Reproduzir vídeo salvo"/>}</details>}
    <p>Trajetos neste navegador. Vídeos no PC, disponíveis novamente ao abrir a apresentação local.</p>
   </div>
  </>}
  <div className="drone56-notice" role="status" aria-live="polite">{state.message||(!busy?notice:'')}</div>
 </aside></>;
}
