import * as T from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
/** Production-only adapter, loaded by the local exporter; not included in the visitor bundle. */
export async function exportApartment73(a:any){
 const model=[...a.interiors.values()].find((m:any)=>m.group.userData.apartment69Ready) as any;
 if(!model||a.scene.userData.lodCount72!==0||a.scene.userData.textureTier72!=='detail')throw new Error('Complete close-range model and detail textures required');
 const root=new T.Group();root.name='EME M14 | Pavimento completo | Web73';
 const floor=model.group.clone(true);floor.name='M14 | Pavimento e sacada';root.add(floor);
 const ceiling=a.floors[14].clone(true);ceiling.name='M14 | Forro preservado';ceiling.visible=true;root.add(ceiling);
 // View-dependent contact decals are a web lighting aid, not architectural geometry.
 const decals:T.Object3D[]=[];root.traverse(o=>{if(o.name==='M14 contact occlusion72')decals.push(o)});decals.forEach(o=>o.removeFromParent());
 const views=Object.entries(model.views).map(([name,v]:[string,any])=>({name,eye:[v.eye[0],v.eye[1]+62.5,v.eye[2]],look:[v.look[0],v.look[1]+62.5,v.look[2]],fov:68}));
 for(const v of views){const c=new T.PerspectiveCamera(v.fov,16/9,.08,2000);c.name='M14 Camera | '+v.name;c.position.fromArray(v.eye);c.lookAt(new T.Vector3().fromArray(v.look));root.add(c);}
 root.updateMatrixWorld(true);const meshes:any[]=[],matrix=new T.Matrix4(),world=new T.Matrix4(),bounds=new T.Box3(),vertex=new T.Vector3();
 root.traverse(o=>{if(!(o instanceof T.Mesh))return;const p=o.geometry.getAttribute('position');const n=o instanceof T.InstancedMesh?o.count:1;bounds.makeEmpty();for(let i=0;i<n;i++){if(o instanceof T.InstancedMesh){o.getMatrixAt(i,matrix);world.multiplyMatrices(o.matrixWorld,matrix)}else world.copy(o.matrixWorld);const ix=o.geometry.index;for(let v=0;v<(ix?.count??p.count);v++)bounds.expandByPoint(vertex.fromBufferAttribute(p,ix?ix.getX(v):v).applyMatrix4(world));}let surfaceArea=0,degenerateTriangles=0;const va=new T.Vector3(),vb=new T.Vector3(),vc=new T.Vector3(),ix=o.geometry.index;for(let i=0;i<n;i++){if(o instanceof T.InstancedMesh){o.getMatrixAt(i,matrix);world.multiplyMatrices(o.matrixWorld,matrix)}else world.copy(o.matrixWorld);for(let k=0;k<(ix?.count??p.count);k+=3){va.fromBufferAttribute(p,ix?ix.getX(k):k).applyMatrix4(world);vb.fromBufferAttribute(p,ix?ix.getX(k+1):k+1).applyMatrix4(world);vc.fromBufferAttribute(p,ix?ix.getX(k+2):k+2).applyMatrix4(world);const area=vb.sub(va).cross(vc.sub(va)).length()/2;surfaceArea+=area;if(area<1e-10)degenerateTriangles++;}}const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials)if(!m.name)m.name='M14 material '+m.uuid.slice(0,8);o.userData.sync73=o.uuid;meshes.push({id:o.uuid,name:o.name,instances:n,surfaceArea,degenerateTriangles,triangles:(o.geometry.index?.count??p.count)/3*n,min:bounds.min.toArray(),max:bounds.max.toArray(),materials:materials.map(m=>({name:m.name,color:(m as T.MeshStandardMaterial).color?.toArray()})),finish:o.userData.finish70??null});});
 const lights:any[]=[];a.scene.traverse((o:any)=>{if(o.isRectAreaLight)lights.push({kind:'area',position:o.position.toArray(),quaternion:o.quaternion.toArray(),width:o.width,height:o.height,color:o.color.toArray(),intensity:o.intensity});if(o.isDirectionalLight&&o.castShadow)lights.push({kind:'sun',position:o.position.toArray(),target:o.target.position.toArray(),color:o.color.toArray(),intensity:o.intensity});});
 const result=await new GLTFExporter().parseAsync(root,{binary:true,onlyVisible:true,maxTextureSize:2048});
 const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(new Blob([result as ArrayBuffer]));});
 return {base64,manifest:{schema:'eme-spatial-blender/1',unit:'m-14',geometryRevision:72,coordinateSystem:'glTF Y-up; Blender import converts to Z-up',baseY:62.5,ceilingY:66,views,meshes,lights,exclusions:['Web contact-occlusion decals; Blender calculates contact lighting'],note:'Production seed from the current complete web floor. No retired cropped study used.'}};
}
