import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {buildCompactVacaria,loadCompactAssets,COMPACT_UNITS} from './vacariaCompactModel';
import {walkStep} from './mWalking';
import './vacaria-viewer.css';
type View='Conjunto'|'Implantação'|'Rua'|'Casa C01'|'Planta 3D'|'Praça'|'Interior';
type Api={go:(v:View)=>void;room:(v:string)=>void;move:(key:string,on:boolean)=>void;light:(value:boolean)=>void};
export default function VacariaCompactViewer(){
 const host=useRef<HTMLDivElement>(null),container=useRef<HTMLDivElement>(null),api=useRef<Api|null>(null);
 const [view,setView]=useState<View>('Conjunto'),[ready,setReady]=useState(false),[error,setError]=useState(''),[zone,setZone]=useState('Sala'),[late,setLate]=useState(false),[full,setFull]=useState(false);
 useEffect(()=>{
  const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch{setError('O navegador não conseguiu iniciar o 3D. A planta e os renders continuam disponíveis.');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;el.appendChild(renderer.domElement);
  const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','Alternativa compacta, 27 casas. Arraste para girar; na visita interna, use as setas ou W A S D.');
  const scene=new T.Scene();scene.background=new T.Color('#dae4e8');const camera=new T.PerspectiveCamera(42,1,.05,400),controls=new OrbitControls(camera,canvas);controls.maxPolarAngle=Math.PI*.49;
  const sun=new T.DirectionalLight('#fff0d8',3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.normalBias=.025;sun.shadow.bias=-.00005;sun.shadow.camera.far=190;scene.add(sun,sun.target);const sky=new T.HemisphereLight('#f7f4e9','#7b816b',1);scene.add(sky);
  const model=buildCompactVacaria();scene.add(model.single,model.district);let disposed=false,current:View='Conjunto',evening=false,frame=0,last=0,yaw=0,pitch=0;const keys=new Set<string>();
  const draw=()=>{if(!disposed&&!document.hidden)renderer.render(scene,camera);};
  let env:T.WebGLRenderTarget|undefined;new RGBELoader().load('/assets/m/materials/daylight-1k.hdr',texture=>{if(disposed){texture.dispose();return;}const gen=new T.PMREMGenerator(renderer);env=gen.fromEquirectangular(texture);scene.environment=env.texture;scene.environmentIntensity=.4;texture.dispose();gen.dispose();draw();});
  loadCompactAssets(model,draw,()=>disposed).catch(e=>{if(!disposed)setError(e.message);});
  function lighting(value:boolean){evening=value;const local=['Casa C01','Planta 3D','Interior'].includes(current);sun.target.position.set(local?0:26,0,local?3:15);sun.position.copy(sun.target.position).add(new T.Vector3(-38,value?24:65,-45));sun.color.set(value?'#ffd197':'#fff0d8');sun.intensity=value?2.4:3;sky.intensity=value?.7:1;model.nightMaterials.forEach(m=>m.emissiveIntensity=value?2.4:1);scene.background=new T.Color(value?'#dbd6c8':'#dae4e8');draw();}
  const look=()=>{camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);};
  function go(next:View){current=next;keys.clear();setView(next);const local=['Casa C01','Planta 3D','Interior'].includes(next);model.single.visible=local;model.district.visible=!local;model.context.visible=next!=='Planta 3D';model.roof.visible=next!=='Planta 3D';renderer.clippingPlanes=next==='Planta 3D'?[new T.Plane(new T.Vector3(0,-1,0),1.15)]:[];
   controls.enabled=next!=='Interior';controls.minDistance=local?3:8;controls.maxDistance=local?35:260;camera.near=next==='Interior'?.05:local?.1:1;camera.fov=next==='Interior'?65:el.clientWidth<600?62:42;camera.updateProjectionMatrix();sun.castShadow=next!=='Planta 3D';sun.shadow.camera.left=local?-16:-70;sun.shadow.camera.right=local?16:70;sun.shadow.camera.top=local?20:95;sun.shadow.camera.bottom=local?-16:-70;sun.shadow.camera.updateProjectionMatrix();
   if(next==='Interior'){camera.position.set(-1.25,1.6,1.25);yaw=Math.PI;pitch=0;setZone('Sala');look();canvas.focus();}else{const positions:Record<Exclude<View,'Interior'>,number[]>={'Conjunto':[80,78,92,27,0,13],'Implantação':[28,195,15.1,28,0,15],'Rua':[60,3.4,3.3,42,1.2,12],'Casa C01':[0,4,-14,0,1.2,1.5],'Planta 3D':[0,21,3.6,0,0,3.7],'Praça':[38,18,71,18,0,55]};const p=positions[next];camera.position.set(p[0],p[1],p[2]);controls.target.set(p[3],p[4],p[5]);controls.update();}lighting(evening);
  }
  function room(name:string){go('Interior');const points:Record<string,number[]>={'Sala':[-1.25,1.6,2.45,0],'Cozinha':[-1.4,1.6,6.2,Math.PI],'Casal':[.5,1.6,5.6,-2.4],'Quarto 2':[1.15,1.6,2.6,-.4],'Rua':[-1.85,1.6,-7.5,Math.PI],'Quintal':[-1.85,1.6,8.8,-.6]};const p=points[name];camera.position.set(p[0],p[1],p[2]);yaw=p[3];pitch=-.08;setZone(name);look();draw();}
  const areas=[{minX:-2.55,maxX:2.55,minZ:-6.2,maxZ:9.7},{minX:-9,maxX:9,minZ:-10.8,maxZ:-5}],bounds={minX:-9,maxX:9,minZ:-10.8,maxZ:9.7};
  function animate(now:number){frame=0;if(disposed)return;const dt=Math.min((now-last)/1000,.05);last=now;if(current==='Interior'&&keys.size){const f=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),s=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),speed=1.7*dt/Math.max(1,Math.hypot(f,s));const next=walkStep({x:camera.position.x,z:camera.position.z},(-Math.sin(yaw)*f+Math.cos(yaw)*s)*speed,(-Math.cos(yaw)*f-Math.sin(yaw)*s)*speed,model.obstacles,bounds,areas);camera.position.x=next.x;camera.position.z=next.z;setZone(next.z<-.15?(next.z<-5?'Rua':'Frente'):next.z>7.8?'Quintal':'Interior');draw();if(!document.hidden)frame=requestAnimationFrame(animate);}}
  const move=(key:string,on:boolean)=>{if(on){keys.add(key);if(!frame){last=performance.now();frame=requestAnimationFrame(animate);}}else keys.delete(key);};const stop=()=>keys.clear();
  const down=(e:KeyboardEvent)=>{if(current==='Interior'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){e.preventDefault();move(e.key.toLowerCase(),true);}};const up=(e:KeyboardEvent)=>move(e.key.toLowerCase(),false);
  let pointer:{x:number;y:number}|null=null;const pd=(e:PointerEvent)=>{if(current==='Interior'){pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}};const pm=(e:PointerEvent)=>{if(!pointer||current!=='Interior')return;yaw-=(e.clientX-pointer.x)*.004;pitch=T.MathUtils.clamp(pitch-(e.clientY-pointer.y)*.004,-1.1,1.1);pointer={x:e.clientX,y:e.clientY};look();draw();};const pu=()=>{pointer=null;};
  const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.fov=current==='Interior'?65:el.clientWidth<600?62:42;camera.updateProjectionMatrix();draw();};const observer=new ResizeObserver(resize);observer.observe(el);controls.addEventListener('change',draw);canvas.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointermove',pm);canvas.addEventListener('pointerup',pu);canvas.addEventListener('pointercancel',pu);
  const fullChange=()=>setFull(document.fullscreenElement===container.current);document.addEventListener('fullscreenchange',fullChange);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();setError('O 3D foi interrompido. Recarregue esta página para reiniciar.');});
  api.current={go,room,move,light:lighting};resize();go('Conjunto');setReady(true);
  (canvas as HTMLCanvasElement&{compact?:unknown}).compact={scene:()=>scene,model:()=>model,camera:()=>camera.position.toArray(),units:COMPACT_UNITS,render:draw};
  return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();window.removeEventListener('keyup',up);window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);document.removeEventListener('fullscreenchange',fullChange);env?.dispose();renderer.dispose();model.dispose();canvas.remove();api.current=null;};
 },[]);
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await container.current?.requestFullscreen();}catch{setError('Tela cheia indisponível. Continue explorando nesta página.');}}
 return <div className="vac-viewer" ref={container}><div className="vac-viewer-toolbar"><div role="group" aria-label="Vistas da alternativa compacta">{(['Conjunto','Implantação','Rua','Casa C01','Planta 3D','Praça']as View[]).map(v=><button key={v} disabled={!ready} aria-pressed={view===v} onClick={()=>api.current?.go(v)}>{v}</button>)}</div><div><button disabled={!ready} aria-pressed={late} onClick={()=>{setLate(!late);api.current?.light(!late)}}>{late?'Luz: fim de tarde':'Luz: dia'}</button><button onClick={fullscreen}>{full?'Sair da tela cheia':'Tela cheia'}</button></div></div><div className="vac-canvas" ref={host}/><div className="vac-model-info"><span>ALTERNATIVA COMPACTA · C1</span><strong>{view==='Interior'?zone:view}</strong><small>{['Conjunto','Implantação','Rua','Praça'].includes(view)?'27 casas · estudo de distribuição':'C01 · 42,12 m² construídos · 2 quartos'}</small></div>{!ready&&!error&&<p role="status">Preparando a alternativa…</p>}{error&&<p className="vac-viewer-error" role="alert">{error}</p>}<div className="vac-viewer-bottom"><p>{view==='Interior'?'Arraste para olhar; caminhe com W A S D, setas ou os controles.':'Arraste para girar. Aproxime com a roda do mouse ou dois dedos.'}</p><button disabled={!ready} onClick={()=>api.current?.go(view==='Interior'?'Casa C01':'Interior')}>{view==='Interior'?'Encerrar visita':'Visitar casa C01'}</button></div>{view==='Interior'&&<><div className="vac-room-stops" aria-label="Ambientes compactos">{['Sala','Cozinha','Casal','Quarto 2','Rua','Quintal'].map(name=><button key={name} onClick={()=>api.current?.room(name)}>{name}</button>)}</div><div className="vac-walk" aria-label="Controles de caminhada">{[['w','Avançar','↑'],['a','Esquerda','←'],['s','Recuar','↓'],['d','Direita','→']].map(([key,label,arrow])=><button key={key} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.move(key,true)}} onPointerUp={()=>api.current?.move(key,false)} onPointerCancel={()=>api.current?.move(key,false)} onLostPointerCapture={()=>api.current?.move(key,false)}>{arrow}</button>)}</div></>}</div>;
}
