import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {buildVacaria,VACARIA_UNITS} from './vacariaModel';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {loadVacariaInterior} from './vacariaInteriorBlender';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {finishVacariaExterior} from './vacariaExterior';
import {finishVacariaHome} from './vacariaFinish';
import {loadVacariaPlanting} from './vacariaPlanting';
import {walkStep} from './mWalking';
import './vacaria-viewer.css';
type View='Implantação'|'Casa'|'Planta 3D'|'Condomínio'|'Entrada'|'Lazer'|'Interior'|'Rua';
type Api={light:(evening:boolean)=>void;go:(v:View)=>void;move:(key:string,on:boolean)=>void;room:(name:string)=>void};
export default function VacariaViewer(){
 const host=useRef<HTMLDivElement>(null),container=useRef<HTMLDivElement>(null),api=useRef<Api|null>(null);
 const [walkZone,setWalkZone]=useState('Sala');
 const [interiorStatus,setInteriorStatus]=useState('');
 const [evening,setEvening]=useState(false);
 const [view,setView]=useState<View>('Condomínio'),[ready,setReady]=useState(false),[error,setError]=useState(''),[unit,setUnit]=useState('V01'),[full,setFull]=useState(false);
 useEffect(()=>{
 const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch{setError('Não foi possível iniciar o 3D neste navegador. As plantas e imagens continuam disponíveis abaixo.');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;el.appendChild(renderer.domElement);
 const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','Modelo 3D do Residencial Vacaria. Arraste para girar ou olhar. Use os botões para mudar de vista.');
 const scene=new T.Scene();scene.background=new T.Color('#dce5e7');const camera=new T.PerspectiveCamera(42,1,.05,350);const controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.maxPolarAngle=Math.PI*.49;
 const skyLight=new T.HemisphereLight('#f6f4e9','#8d907e',.75);scene.add(skyLight);const sun=new T.DirectionalLight('#ffe3b7',3.3);sun.position.set(-14,22,-12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-60;sun.shadow.camera.far=160;sun.shadow.normalBias=.025;sun.shadow.bias=-.00005;scene.add(sun,sun.target);
 const model=buildVacaria();scene.add(model.single,model.district);let current:View='Casa',frame=0,disposed=false,yaw=0,pitch=0,last=0;const keys=new Set<string>();
 const draw=()=>{if(disposed||document.hidden)return;renderer.render(scene,camera);};
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
 const finish=finishVacariaHome(model,draw);const exterior=finishVacariaExterior(model);loadVacariaPlanting(model,draw,()=>disposed).catch(()=>{if(!disposed)setError('Não foi possível carregar a vegetação. Reinicie a exploração para tentar novamente.');});
 let hdrEnv:T.WebGLRenderTarget|undefined;new RGBELoader().load('/assets/m/materials/daylight-1k.hdr',texture=>{if(disposed){texture.dispose();return;}const generator=new T.PMREMGenerator(renderer);hdrEnv=generator.fromEquirectangular(texture);scene.environment=hdrEnv.texture;texture.dispose();generator.dispose();draw();},undefined,()=>{});
 let late=false;function lighting(value:boolean){late=value;const local=['Casa','Planta 3D','Interior'].includes(current);const target=local?new T.Vector3(0,0,2):current==='Rua'?new T.Vector3(42,0,7):new T.Vector3(26,0,15);sun.target.position.copy(target);sun.position.copy(target).add(new T.Vector3(late?-38:-38,late?24:65,late?-42:-50));sun.color.set(late?'#ffcd91':'#fff0d4');sun.intensity=late?2.3:3.1;skyLight.intensity=late?.5:.75;scene.environmentIntensity=late?.36:.48;scene.background=new T.Color(late?'#d8d6ce':'#d9e4eb');exterior.nightMaterials.forEach(m=>m.emissiveIntensity=late?2.5:1.1);draw();}
 const indoorLight=new T.HemisphereLight('#fff1da','#897e69',.7);model.single.add(indoorLight);
 let interiorLoaded=false,interiorLoading=false;const ensureInterior=()=>{if(interiorLoaded||interiorLoading)return;interiorLoading=true;setInteriorStatus('Carregando os acabamentos do interior…');loadVacariaInterior(model,draw,()=>disposed).then(()=>{if(!disposed){interiorLoaded=true;setInteriorStatus('');}}).catch(()=>{if(!disposed)setInteriorStatus('Acabamentos indisponíveis. A visita básica continua disponível; tente entrar novamente.');}).finally(()=>{interiorLoading=false;});};
 const look=()=>{camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);};
 function go(v:View){current=v;keys.clear();sun.castShadow=v!=='Planta 3D';setView(v);const local=['Casa','Planta 3D','Interior'].includes(v);camera.near=v==='Interior'?.05:local?.15:1;camera.fov=v==='Interior'?60:el.clientWidth<600?62:42;camera.updateProjectionMatrix();sun.shadow.camera.left=local?-14:v==='Rua'?-35:-60;sun.shadow.camera.right=local?14:v==='Rua'?35:60;sun.shadow.camera.top=local?18:v==='Rua'?35:90;sun.shadow.camera.bottom=local?-14:v==='Rua'?-35:-60;sun.shadow.camera.updateProjectionMatrix();finish.context.visible=v==='Casa'||v==='Interior';finish.ground.visible=v==='Casa'||v==='Interior';finish.road.visible=v==='Casa'||v==='Interior';finish.sidewalk.visible=v==='Casa'||v==='Interior';model.single.visible=local;model.district.visible=!local;model.roof.visible=v!=='Planta 3D';model.caps.visible=v==='Planta 3D';renderer.clippingPlanes=v==='Planta 3D'?[new T.Plane(new T.Vector3(0,-1,0),1.15)]:[];controls.enabled=v!=='Interior';controls.minDistance=local?3:8;controls.maxDistance=local?35:260;controls.maxPolarAngle=Math.PI*.49;
 if(v==='Interior'){setWalkZone('Sala');ensureInterior();camera.position.set(-1.25,1.65,1.2);yaw=Math.PI;pitch=0;look();canvas.focus();}else{const presets:Record<Exclude<View,'Interior'>,number[]>={'Implantação':[28,195,15.1,28,0,15],'Casa':[0,3.7,-14,0,1.25,1],'Planta 3D':[0,22,2.15,0,0,2.25],'Condomínio':[78,75,90,27,0,12],'Entrada':[1.2,4,-56,2,1,-25],'Lazer':[43,21,73,21,0,55],'Rua':[59,3.2,3,41,1.2,12]};const p=presets[v];camera.position.set(p[0],p[1],p[2]);controls.target.set(p[3],p[4],p[5]);controls.update();}lighting(late);}
 const walkBounds={minX:-10.5,maxX:10.5,minZ:-10.9,maxZ:10.2};
 const walkAreas=[{minX:-2.86,maxX:2.86,minZ:-6.3,maxZ:10.2},{minX:-10.5,maxX:10.5,minZ:-10.9,maxZ:-5}];
 const walkObstacles=[...model.obstacles,{minX:.25,maxX:2.25,minZ:-4.8,maxZ:-.2}];
 const zoneAt=(z:number)=>z<-.15?(z<-5?'Rua':'Jardim frontal'):z>7.55?'Quintal':'Interior';
 function animate(now:number){frame=0;if(disposed)return;const dt=Math.min((now-last)/1000,.05);last=now;if(current==='Interior'&&keys.size){const f=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),s=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));const speed=1.8*dt/Math.max(1,Math.hypot(f,s));const next=walkStep({x:camera.position.x,z:camera.position.z},(-Math.sin(yaw)*f+Math.cos(yaw)*s)*speed,(-Math.cos(yaw)*f-Math.sin(yaw)*s)*speed,walkObstacles,walkBounds,walkAreas);camera.position.x=next.x;camera.position.z=next.z;setWalkZone(zoneAt(next.z));draw();if(!document.hidden)frame=requestAnimationFrame(animate);}}
 const move=(key:string,on:boolean)=>{if(on){keys.add(key);if(!frame){last=performance.now();frame=requestAnimationFrame(animate);}}else keys.delete(key);};
 const stop=()=>keys.clear();const down=(e:KeyboardEvent)=>{if(current==='Interior'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){e.preventDefault();move(e.key.toLowerCase(),true);}};const up=(e:KeyboardEvent)=>move(e.key.toLowerCase(),false);
 let pointer:{x:number;y:number;startX:number;startY:number}|null=null;
 const pd=(e:PointerEvent)=>{pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};if(current==='Interior')canvas.setPointerCapture(e.pointerId);};
 const pm=(e:PointerEvent)=>{if(!pointer||current!=='Interior')return;yaw-=(e.clientX-pointer.x)*.004;pitch=T.MathUtils.clamp(pitch-(e.clientY-pointer.y)*.004,-1.1,1.1);pointer.x=e.clientX;pointer.y=e.clientY;look();draw();};
 const pu=(e:PointerEvent)=>{if(pointer&&current!=='Interior'&&model.district.visible&&Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)<8){const r=canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(model.homes,true)[0];if(hit){let o:T.Object3D|null=hit.object;while(o&&!o.userData.unitId)o=o.parent;if(o){setUnit(o.userData.unitId);if(o.userData.unitId==='V01')go('Casa');}}}pointer=null;};
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=current==='Interior'?60:w<600?62:42;camera.updateProjectionMatrix();draw();};const observer=new ResizeObserver(resize);observer.observe(el);controls.addEventListener('change',draw);canvas.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointermove',pm);canvas.addEventListener('pointerup',pu);canvas.addEventListener('pointercancel',()=>{pointer=null;stop();});
 const lost=(e:Event)=>{e.preventDefault();setError('A visualização 3D foi interrompida. Encerre e inicie a exploração novamente.');};canvas.addEventListener('webglcontextlost',lost);
 const fullChange=()=>setFull(document.fullscreenElement===container.current);document.addEventListener('fullscreenchange',fullChange);
 const roomGo=(name:string)=>{go('Interior');const stops:Record<string,number[]>={'Sala':[-1.30,1.6,2.5,0],'Cozinha':[-1.5,1.65,5.15,Math.PI],'Casal':[1.04,1.6,4.98,-2.50],'Quarto 2':[1.35,1.6,2.35,-.70],'Ir para a rua':[-2.18,1.65,-7.3,Math.PI],'Ir ao quintal':[-1.8,1.65,9.5,-.55]};const p=stops[name];setWalkZone(name==='Ir para a rua'?'Rua':name==='Ir ao quintal'?'Quintal':name);camera.position.set(p[0],p[1],p[2]);yaw=p[3];pitch=name==='Casal'||name==='Quarto 2'?-.32:-.10;look();draw();};api.current={go,move,room:roomGo,light:lighting};resize();go('Condomínio');setReady(true);
 // Read-only diagnostics for geometry/navigation acceptance; no persistent scene state.
 const diagnostics={units:VACARIA_UNITS.length,house:{width:6,depth:7.5},camera:()=>camera.position.toArray(),scene:()=>scene,render:draw};(canvas as HTMLCanvasElement&{vacaria?:unknown}).vacaria=diagnostics;
 return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();window.removeEventListener('keyup',up);window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);document.removeEventListener('fullscreenchange',fullChange);finish.dispose();hdrEnv?.dispose();env.dispose();renderer.dispose();model.dispose();canvas.remove();api.current=null;};
 },[]);
 async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(container.current?.requestFullscreen)await container.current.requestFullscreen();else setError('Tela cheia indisponível neste navegador. Continue explorando nesta página.');}catch{setError('Não foi possível abrir a tela cheia. Continue explorando nesta página.');}}
 return <div className="vac-viewer" ref={container}><div className="vac-viewer-toolbar"><div role="group" aria-label="Vistas do modelo">{(['Condomínio','Implantação','Rua','Casa','Planta 3D','Entrada','Lazer'] as View[]).map(v=><button key={v} disabled={!ready} aria-pressed={view===v} onClick={()=>api.current?.go(v)}>{v}</button>)}</div><div><button disabled={!ready} aria-pressed={evening} onClick={()=>{setEvening(!evening);api.current?.light(!evening)}}>{evening?'Luz: fim de tarde':'Luz: dia'}</button><button onClick={toggleFull}>{full?'Sair da tela cheia':'Tela cheia'}</button></div></div><div ref={host} className="vac-canvas"/>{interiorStatus&&<p role="status" className="vac-interior-status">{interiorStatus}</p>}{!ready&&!error&&<p role="status">Preparando o modelo…</p>}{error&&<p className="vac-viewer-error" role="alert">{error}</p>}<div className="vac-model-info"><span>RESIDENCIAL VACARIA · V08</span><strong>{view==='Interior'?walkZone:view==='Planta 3D'?'Corte da casa a 1,15 m':view}</strong><small>{['Condomínio','Implantação','Rua','Entrada','Lazer'].includes(view)?'24 casas representadas · implantação em estudo':'Casa-base · 6,00 × 7,50 m · 45 m²'}</small></div><div className="vac-viewer-bottom"><p>{view==='Interior'?'Caminhe pelas portas até a rua e o quintal. Arraste para olhar; use W A S D, setas ou os controles.':'Arraste para girar. Use a roda do mouse ou dois dedos para aproximar.'}</p><div><span>{unit==='V01'?'V01 · Casa demonstrativa':`${unit} · contexto externo`}</span><button disabled={!ready} onClick={()=>{setUnit('V01');api.current?.go(view==='Interior'?'Casa':'Interior')}}>{view==='Interior'?'Encerrar visita':'Visitar casa V01'}</button></div></div>{view==='Interior'&&<div className="vac-room-stops" aria-label="Ambientes da casa demonstrativa">{['Sala','Cozinha','Casal','Quarto 2','Ir para a rua','Ir ao quintal'].map(name=><button key={name} onClick={()=>api.current?.room(name)}>{name}</button>)}</div>}{view==='Interior'&&<div className="vac-walk" aria-label="Controles de caminhada">{[['w','Avançar','↑'],['a','Esquerda','←'],['s','Recuar','↓'],['d','Direita','→']].map(([k,label,arrow])=><button key={k} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.move(k,true)}} onPointerUp={()=>api.current?.move(k,false)} onPointerCancel={()=>api.current?.move(k,false)} onLostPointerCapture={()=>api.current?.move(k,false)}>{arrow}</button>)}</div>}</div>;
}
