import {lazy,Suspense,useEffect,useState} from 'react';
import {ArrowDown,ArrowUpRight,BedDouble,House,Layers,Ruler} from 'lucide-react';
import './vacaria.css';
import './vacaria-compact.css';
const Viewer=lazy(()=>import('./VacariaCompactViewer'));
const original='/apresentar/residencial-vacaria';
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
function Plan(){return <svg className="vc-plan" viewBox="0 0 700 1010" role="img" aria-labelledby="vc-plan-title vc-plan-desc"><title id="vc-plan-title">Planta esquemática da casa compacta de 42,12 metros quadrados</title><desc id="vc-plan-desc">5,40 por 7,80 metros externos. Sala e cozinha integradas à direita. Quarto de casal nos fundos à esquerda, banheiro no centro e segundo quarto à frente. Uma janela e uma porta na fachada. Aberturas e mobiliário correspondem ao modelo C01; ventilação do banheiro a resolver.</desc>
 <rect width="700" height="1010" fill="#f7f5ee"/><g fontFamily="Arial,sans-serif" fill="#243f31" fontSize="19">
 <text x="350" y="34" textAnchor="middle">QUINTAL · saída pela cozinha</text><g transform="translate(680 0) scale(-1 1)"><rect x="70" y="60" width="540" height="780" fill="#e6dfd0" stroke="#294334" strokeWidth="15"/>
 <rect x="85" y="75" width="250" height="750" fill="#eee9dd"/><rect x="350" y="75" width="245" height="300" fill="#e0e5d6"/><rect x="350" y="390" width="245" height="135" fill="#d8e2de"/><rect x="350" y="540" width="245" height="285" fill="#e0e5d6"/>
 <g stroke="#294334" strokeWidth="15"><path d="M342.5 75V275 M342.5 355V425 M342.5 505V550 M342.5 630V825 M350 382.5H595 M350 532.5H595"/></g>
 <g fill="#b8c5ad" stroke="#75866d" strokeWidth="2"><rect x="390" y="90" width="138" height="188" rx="5"/><rect x="401" y="104" width="115" height="36" rx="8"/><rect x="370" y="310" width="170" height="55"/><rect x="494" y="607" width="88" height="188" rx="4"/><rect x="502" y="745" width="72" height="35" rx="6"/><rect x="350" y="662" width="60" height="110"/></g>
 <g fill="#d0b897" stroke="#9c886d" strokeWidth="2"><rect x="88" y="586" width="72" height="160" rx="8"/><rect x="282" y="624" width="40" height="110"/><rect x="165" y="417" width="75" height="100" rx="5"/><rect x="170" y="390" width="65" height="25"/><rect x="170" y="522" width="65" height="25"/><rect x="270" y="86" width="60" height="205"/><rect x="88" y="240" width="65" height="65"/></g>
 <g fill="#f5f4ed" stroke="#749085" strokeWidth="2"><rect x="288" y="110" width="30" height="45"/><rect x="284" y="234" width="37" height="45"/><rect x="495" y="396" width="90" height="120"/><ellipse cx="389" cy="433" rx="22" ry="29"/><rect x="360" y="481" width="54" height="35"/></g>
 <g stroke="#77a0a1" strokeWidth="6"><path d="M360 840H550 M420 60H560 M225 60H315"/></g><g stroke="#f7f5ee" strokeWidth="17"><path d="M110 840H200 M110 60H200"/></g><g fill="none" stroke="#9c886d" strokeWidth="2"><path d="M110 840V750 Q200 750 200 840 M110 60V150 Q200 150 200 60 M342 275H422 Q422 355 342 355 M342 425H422 Q422 505 342 505 M342 550H422 Q422 630 342 630"/></g>
 </g><g fontSize="17" textAnchor="middle"><text x="205" y="294">Casal · 7,35 m²</text><text x="210" y="572">Quarto 2 · 6,98 m²</text><text x="215" y="474">Banho · 3,31 m²</text><text x="482" y="355">Sala + cozinha</text><text x="482" y="378">18,75 m²</text></g>
 <g fill="none" stroke="#63765e" strokeWidth="1.5"><path d="M70 877H610 M70 860V890 M610 860V890 M650 60V840 M630 60H663 M630 840H663"/></g><text x="340" y="904" textAnchor="middle">5,40 m</text><text x="674" y="465" textAnchor="middle" transform="rotate(90 674 465)">7,80 m</text><text x="350" y="945" textAnchor="middle">FRENTE · vaga aberta + acesso</text><text x="350" y="978" textAnchor="middle" fontSize="15">Esquema de estudo · dimensões internas nominais</text></g></svg>;}
export default function VacariaCompactPage(){
 const [started,setStarted]=useState(false),[cost,setCost]=useState('3400'),[swap,setSwap]=useState('0'),[other,setOther]=useState('');
 useEffect(()=>{const old=document.title;document.title='Vacaria · Alternativa compacta C1 | EME Select';return()=>{document.title=old;};},[]);
 const valid=cost!==''&&Number(cost)>0&&swap!==''&&Number.isInteger(Number(swap))&&Number(swap)>=0&&Number(swap)<24&&(other===''||Number(other)>=0);
 const revenue=(27-Number(swap))*170000,build=27*42.12*Number(cost),balance=revenue-build,result=balance-Number(other);
 return <div className="vac-page vc-page"><a className="vac-skip" href="#vc-main">Pular para o conteúdo</a><header className="vac-header"><a href="/" className="vac-brand">EME<span>SELECT</span></a><nav aria-label="Alternativa compacta"><a href="#proposta">Proposta</a><a href="#planta">Planta</a><a href="#spatial">Explorar 3D</a><a href="#custos">Custos</a></nav></header>
 <nav className="vac-variant-nav" aria-label="Versões do empreendimento"><a href={original}>Projeto original · 24 casas</a><a aria-current="page" href="?alternativa=compacta">Alternativa compacta · 27 casas</a><span>Estudos independentes</span></nav>
 <main id="vc-main"><section className="vac-hero"><div className="vac-hero-copy"><span className="vac-eyebrow">Alternativa compacta · C1</span><p className="vac-location">Vacaria · Rio Grande do Sul</p><h1>Mais eficiência.<br/><em>O mesmo lugar.</em></h1><p className="vac-lead">Uma casa essencial.<br/>Um conjunto mais bem aproveitado.</p><p className="vac-summary">27 casas de 42,12 m², módulos repetidos e espaços comuns de manutenção simples. Uma alternativa para comparar com o projeto original.</p><a className="vac-button" href="#spatial">Explorar a alternativa <ArrowDown size={17}/></a><span className="vac-hero-note">Estudo conceitual · não constitui oferta de venda</span></div><figure className="vac-hero-image"><img src="/assets/vacaria/compacta-c1-conjunto.webp" alt="Render da alternativa compacta, com dez casas na primeira linha, nove na linha central e oito próximas à praça" fetchPriority="high"/><figcaption><span>Implantação C1 · modelo próprio</span><span>Blender / Cycles</span></figcaption></figure></section>
 <div className="vac-facts"><div><House size={22}/><strong>27 casas</strong><span>3 a mais no estudo</span></div><div><Ruler size={22}/><strong>42,12 m²</strong><span>Construídos por casa</span></div><div><BedDouble size={22}/><strong>2 quartos</strong><span>Frente e fundos</span></div><div><Layers size={22}/><strong>−6,4% de área</strong><span>Por casa, frente à original</span></div></div>
 <section id="proposta" className="vac-section"><div className="vac-section-head"><div><span className="vac-eyebrow">01 — Implantação e construção</span><h2>Repetir melhor.<br/><em>Construir com clareza.</em></h2></div><p>O contorno do terreno e o acesso permanecem como referência. A C1 reorganiza as fileiras e a rua central para testar três novas unidades.</p></div><div className="vc-principles"><article><span>01 / Módulo</span><h3>5,40 × 7,80 m</h3><p>Planta retangular, uma janela e uma porta na fachada. Cobertura metálica contínua por módulo e forro leve como hipótese construtiva, sem laje de cobertura no modelo.</p></article><article><span>02 / Distribuição</span><h3>10 + 9 + 8 casas</h3><p>Ruas de 4,80 m, calçadas de 1,20 m e vagas de 5 m de profundidade representadas separadamente. Dimensões de estudo, com manobras e exigências locais a conferir.</p></article><article><span>03 / Espaços comuns</span><h3>Lazer essencial</h3><p>Playground, bancos, mesa e iluminação. Sem pergolado ou salão nesta alternativa. Quintais de ponta aproveitam as divisas, sem duplicar o muro perimetral.</p></article></div><p className="vac-small">A contagem verifica o modelo esquemático disponível, não a capacidade legal ou topográfica do terreno. Estrutura, isolamento térmico/acústico, drenagem e acessibilidade dependem de projeto técnico.</p></section>
 <section id="planta" className="vac-section vac-plans"><div className="vac-section-head"><div><span className="vac-eyebrow">02 — Casa C01</span><h2>Uma planta menor.<br/><em>Com função em cada espaço.</em></h2></div><p>Ambientes e mobiliário foram reorganizados para a largura compacta. A área construída inclui paredes; a soma nominal dos ambientes é de aproximadamente 36,39 m².</p></div><div className="vac-plan-layout"><figure><Plan/><figcaption>Planta esquemática correspondente ao modelo C01. A representação não substitui desenho executivo.</figcaption></figure><aside><h3>O essencial, organizado.</h3><dl>{[['Sala, jantar e cozinha','2,50 × 7,50 m · inclui circulação','18,75 m²'],['Quarto de casal','2,45 × 3,00 m','7,35 m²'],['Segundo quarto','2,45 × 2,85 m','6,98 m²'],['Banheiro','2,45 × 1,35 m','3,31 m²']].map(([name,dim,area])=><div key={name}><dt>{name}<small>{dim}</small></dt><dd>{area}</dd></div>)}</dl><p className="vac-small">Cozinha e banheiro próximos à mesma parede de instalações. Ventilação do banheiro, áreas mínimas, circulação junto aos móveis e requisitos do financiamento precisam ser compatibilizados antes de consolidar a planta.</p><a className="vac-text-link" href="#spatial" onClick={()=>setStarted(true)}>Conhecer a C01 em 3D <ArrowUpRight size={17}/></a></aside></div></section>
 <section id="spatial" className="vac-section vac-spatial"><div className="vac-section-head"><div><span className="vac-eyebrow">03 — EME Spatial · alternativa C1</span><h2>Compare por dentro.<br/><em>Explore o conjunto.</em></h2></div><p>Implantação própria com 27 casas e uma unidade demonstrativa. Alterne entre o conjunto, a planta e a visita à C01, com acesso à rua e ao quintal.</p></div>{started?<Suspense fallback={<p role="status">Carregando a alternativa compacta…</p>}><Viewer/></Suspense>:<div className="vac-spatial-stage"><img src="/assets/vacaria/compacta-c1-rua.webp" alt="Rua e fachadas da alternativa compacta" loading="lazy"/><div><span className="vac-status">C01 · 42,12 m²</span><h3>Outra forma<br/>de aproveitar.</h3><p>Uma alternativa separada, com fachadas fiéis à referência e uma planta compacta para avaliação.</p><button className="vac-button vac-button-light" onClick={()=>setStarted(true)}>Explorar alternativa 3D <ArrowUpRight size={17}/></button></div></div>}<div className="vac-3d-actions"><p>Estudo C1 · quantidade e dimensões sujeitas à conferência. <a href="/assets/vacaria/CREDITOS-v6.html" target="_blank" rel="noreferrer">Veículo 3D</a> · <a href="/assets/vacaria/CREDITOS-v7.html" target="_blank" rel="noreferrer">Vegetação da biblioteca</a>.</p>{started&&<button onClick={()=>setStarted(false)}>Encerrar exploração</button>}<a className="vac-text-link" href={original+'#spatial'}>Abrir o projeto original ↗</a></div><div className="vc-renders">{[['rua','Fachadas compactas'],['conjunto','Nova distribuição do conjunto']].map(([id,label])=><figure key={id}><a href={`/assets/vacaria/compacta-c1-${id}.webp`} target="_blank" rel="noreferrer"><img src={`/assets/vacaria/compacta-c1-${id}.webp`} alt={label} loading="lazy"/></a><figcaption>{label} · render do modelo C1</figcaption></figure>)}</div></section>
 <section id="custos" className="vac-section"><div className="vac-section-head"><div><span className="vac-eyebrow">04 — Estudo de custos</span><h2>Preço como meta.<br/><em>Custo como decisão.</em></h2></div><p>R$ 170 mil por casa é a meta comercial informada, sem promessa de financiamento ou rentabilidade. Permuta e demais despesas seguem em definição.</p></div><div className="vc-comparison"><table><caption>Comparação física e construção a R$ 3.400/m²</caption><thead><tr><th>Indicador</th><th>Original V08</th><th>Compacta C1</th></tr></thead><tbody><tr><th>Casas representadas</th><td>24</td><td>27</td></tr><tr><th>Área por casa</th><td>45 m²</td><td>42,12 m²</td></tr><tr><th>Área construída total</th><td>1.080 m²</td><td>1.137,24 m²</td></tr><tr><th>Construção por casa</th><td>{money(153000)}</td><td>{money(143208)}</td></tr><tr><th>Construção de todas as casas</th><td>{money(3672000)}</td><td>{money(3866616)}</td></tr></tbody></table></div><p className="vc-cost-note">A casa reduz 6,4% da área; o conjunto aumenta 5,3% da área construída por ter três unidades a mais. O custo por m² foi mantido igual apenas para comparação: a redução real exige orçamento por serviços.</p>
 <div className="vc-budget"><div><h3>Teste a conta da C1.</h3><div className="vc-fields"><label>Construção das casas · R$/m²<input type="number" min="1" step="any" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Casas em permuta · hipótese<input type="number" min="0" max="23" step="1" value={swap} onChange={e=>setSwap(e.target.value)}/></label><label className="vc-field-wide">Demais despesas do empreendimento · R$<input type="number" min="0" step="any" value={other} placeholder="A orçar — não considerado zero" onChange={e=>setOther(e.target.value)}/></label></div><p className="vac-small">Incluir infraestrutura, projetos, tributos, vendas, administração, juros, contingência e eventual complemento da permuta. Evitar duplicar itens incluídos nos R$/m². Permuta inicial zero é apenas referência de cálculo.</p></div><div aria-live="polite">{valid?<dl><div><dt>Receita de {27-Number(swap)} vendas</dt><dd>{money(revenue)}</dd></div><div><dt>Construção das 27 casas</dt><dd>{money(build)}</dd></div><div><dt>Saldo antes das demais despesas</dt><dd>{money(balance)}</dd></div><div className="vc-result"><dt>{other===''?'Resultado ainda não apurado':'Resultado do cenário'}</dt><dd>{other===''?'Falta orçamento':money(result)}</dd>{other!==''&&<small>{(result/revenue*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}% da receita · valores nominais</small>}</div></dl>:<p role="alert">Informe custo positivo, permuta inteira entre 0 e 23 e despesas não negativas.</p>}</div></div>
 </section></main><footer className="vac-footer"><a className="vac-brand" href="/">EME<span>SELECT</span></a><p>Alternativa compacta C1 · estudo conceitual independente.<br/>Renders ilustrativos do modelo. Não constitui oferta de venda.</p><a href={original}>Voltar ao projeto original <ArrowUpRight size={16}/></a></footer></div>;
}

