export const solutions = [
 {id:'edificios',name:'Edifícios',image:'torre',tag:'ARQUITETURA EM NOVA ESCALA',headline:'Grandes projetos. Novas perspectivas.',description:'Apresente a torre, as unidades e as áreas comuns em uma experiência que aproxima as pessoas do empreendimento.',scope:['Fachadas e volumetria','Apartamentos e tipologias','Áreas comuns','Apresentação para lançamento'],experience:'/apresentar/m',demo:'Explorar a Torre M'},
 {id:'mixed-use',name:'Mixed Use',image:'marketing/mixed-use',tag:'MORAR, TRABALHAR E CONVIVER',headline:'Diferentes usos. Um novo lugar.',description:'Comércio, serviços e residências conectados em um mesmo conceito. Desenvolva e apresente a relação entre os espaços.',scope:['Implantação e acessos','Comércio e serviços','Residências e convivência','Apresentação do conceito'],experience:'',demo:'Modelo autoral em desenvolvimento'},
 {id:'casas',name:'Casas',image:'marketing/hero-casa',tag:'DO SEU JEITO, DESDE O COMEÇO',headline:'Sua casa começa com uma visão.',description:'Do zero, da planta ou de um espaço existente. Explore a fachada, os interiores e as possibilidades de viver no seu próximo lugar.',scope:['Conceito e distribuição','Fachada e área externa','Interiores e mobiliário','Imagens e experiência 3D'],experience:'/apresentar/residencial-vacaria',demo:'Explorar estudo residencial'},
 {id:'condominios',name:'Condomínios e loteamentos',image:'marketing/condominio',tag:'O PROJETO ALÉM DA UNIDADE',headline:'Um lugar inteiro para descobrir.',description:'Visualize a implantação, a circulação e os espaços coletivos antes da construção. Apresente como cada parte se conecta ao conjunto.',scope:['Implantação e lotes','Casas e unidades','Paisagismo e lazer','Percursos aéreos virtuais'],experience:'/apresentar/patio-m',demo:'Explorar o Pátio M'},
 {id:'interiores',name:'Interiores',image:'marketing/torre-sala',tag:'ESCOLHAS QUE TRANSFORMAM ESPAÇOS',headline:'Experimente antes de escolher.',description:'Compare composições, materiais e mobiliário para entender como cada escolha pode transformar o seu ambiente.',scope:['Layout e mobiliário','Cores e acabamentos','Imagens de interiores','Configuração e comparação'],experience:'/apresentar/m?apartamento=14&personalizar=1',demo:'Personalizar apartamento da Torre M'},
];
export const offerings=[
 {id:'visual',name:'Básico',subtitle:'Visualize e configure',image:'marketing/casa-basico',features:['3D leve com rotação e aproximação','Interiores por vistas fixas ou superiores','Opções de materiais e mobiliário','Percurso externo de drone virtual'],note:'Sem caminhada interna. Realismo leve e opções definidas no escopo.'},
 {id:'interactive',name:'Interativo',subtitle:'Entre e explore',image:'marketing/casa-interativo',features:['Navegação pelos ambientes contratados','Materiais e iluminação mais detalhados','Personalização durante a experiência','Percursos de câmera externos e internos'],note:'Ambientes, configurações e percursos definidos por projeto.'},
 {id:'signature',name:'Pro',subtitle:'Apresente com alto realismo',image:'marketing/casa-pro',features:['Modelagem e acabamento visual avançados','Materiais e iluminação refinados','Interações e apresentação personalizadas','Produção audiovisual com direção de câmera'],note:'Produção especializada. Realismo e desempenho ajustados à entrega.'},
];
export const deliveries=['Planta de apresentação','Imagens externas','Imagens internas','Modelo 3D','Experiência imersiva','Configuração de interiores','Vídeo drone virtual','Vídeo de ambientes'];
export const starts=[{name:'Tenho uma ideia',desc:'Quero desenvolver um conceito do zero.',icon:'idea'},{name:'Tenho uma planta',desc:'Quero visualizar e explorar meu projeto.',icon:'plan'},{name:'Tenho fotos e medidas',desc:'Quero transformar um espaço existente.',icon:'photo'},{name:'Tenho um modelo 3D',desc:'Quero refinar e apresentar meu projeto.',icon:'box'}];
export const audiences=['Pessoas físicas','Arquitetos e designers','Construtoras e incorporadoras','Urbanizadoras','Condomínios','Empresas, lojas e marcas'];
