import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight,Box,Check,ChevronRight,Download,Expand,Image as ImageIcon,Leaf,Play,Share2,Sun,TreePine,X} from 'lucide-react';
import './botanique.css';
import type {BotaniqueNavigationData} from './botaniqueNavigation';
import type {BotaniqueLightFixture} from './botaniqueLighting';

export type BotaniqueVector=[number,number,number];
export type BotaniqueView={id:string;label:string;position:BotaniqueVector;target:BotaniqueVector};
export type BotaniqueScene={url:string;camera:{position:BotaniqueVector;target:BotaniqueVector};views:BotaniqueView[];bounds?:{min:BotaniqueVector;max:BotaniqueVector};rooms?:BotaniqueView[];navigation?:BotaniqueNavigationData;walkEntries?:BotaniqueView[];modeledLights?:BotaniqueLightFixture[];floorContext?:{id:string;label:string;levelsBelow:number;note:string}};
export type BotaniqueImage={url:string;title:string;credit?:string;kind:'render'|'reference'};
export type BotaniqueManifest={project:string;version:string;disclaimer:string;scenes:Partial<Record<'exterior'|'apartamento',BotaniqueScene>>;images:BotaniqueImage[];hero?:string;video?:{url:string;poster?:string};presentation?:{url:string;label?:string}};
const Viewer=lazy(()=>import('./BotaniqueViewer'));
const assetRoot='/assets/botanique/';
const empty:BotaniqueManifest={project:'Botanique Home Resort',version:'demo-01',disclaimer:'Estudo demonstrativo EME Spatial baseado em referências públicas. Dimensões e ambientação estimadas.',scenes:{},images:[]};
const localAsset=(url:unknown):url is string=>typeof url==='string'&&url.startsWith(assetRoot)&&!url.includes('..');
function readManifest(value:unknown):BotaniqueManifest{
 if(!value||typeof value!=='object')throw Error('Material de apresentação indisponível.');
 const data=value as BotaniqueManifest;
 if(!data.scenes||typeof data.scenes!=='object')throw Error('A experiência está sendo preparada.');
 for(const key of ['exterior','apartamento']as const){const scene=data.scenes[key];if(scene&&(!localAsset(scene.url)||!scene.camera||!Array.isArray(scene.camera.position)||!Array.isArray(scene.camera.target)))throw Error('Não foi possível validar a experiência.');}
 return {...empty,...data,video:data.video&&localAsset(data.video.url)&&data.video.url.split('?')[0].endsWith('.mp4')?{url:data.video.url,poster:localAsset(data.video.poster)?data.video.poster:undefined}:undefined,presentation:data.presentation&&localAsset(data.presentation.url)&&data.presentation.url.endsWith('.pdf')?data.presentation:undefined,images:Array.isArray(data.images)?data.images.filter(i=>localAsset(i.url)&&['render','reference'].includes(i.kind)):[]};
}
export default function BotaniquePage(){
 const [manifest,setManifest]=useState<BotaniqueManifest>(empty),[loading,setLoading]=useState(true),[failure,setFailure]=useState(''),[active,setActive]=useState<'exterior'|'apartamento'>(()=>new URLSearchParams(location.search).get('cena')==='apartamento'?'apartamento':'exterior'),[opened,setOpened]=useState(()=>['exterior','apartamento'].includes(new URLSearchParams(location.search).get('cena')||'')),[lightbox,setLightbox]=useState<number|null>(null),[notice,setNotice]=useState('');
 const experience=useRef<HTMLElement>(null),closeImage=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const abort=new AbortController();document.title='Botanique Home Resort · EME Spatial';fetch(assetRoot+'manifest.json',{signal:abort.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('A apresentação está sendo preparada. Volte em alguns instantes.');return r.json();}).then(data=>setManifest(readManifest(data))).catch(e=>{if(e.name!=='AbortError')setFailure(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[]);
 useEffect(()=>{if(lightbox===null)return;const before=document.activeElement as HTMLElement|null;closeImage.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setLightbox(null);if(event.key==='ArrowRight')setLightbox(i=>i===null?null:(i+1)%manifest.images.length);if(event.key==='ArrowLeft')setLightbox(i=>i===null?null:(i-1+manifest.images.length)%manifest.images.length);};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;before?.focus();};},[lightbox,manifest.images.length]);
 useEffect(()=>{const change=()=>{const scene=new URLSearchParams(location.search).get('cena');if(scene==='exterior'||scene==='apartamento'){setActive(scene);setOpened(true);}else setOpened(false);};window.addEventListener('popstate',change);return()=>window.removeEventListener('popstate',change);},[]);
 const hero=manifest.images.find(i=>i.url===manifest.hero)||manifest.images.find(i=>i.kind==='reference'&&/fachada|torre|exterior/i.test(i.title))||manifest.images.find(i=>i.kind==='render'&&/fachada|torre|exterior|conjunto/i.test(i.title))||manifest.images[0];
 const heroLabel=hero?.kind==='render'?'VISUALIZAÇÃO EME SPATIAL':'REFERÊNCIA DO EMPREENDIMENTO';
 function explore(scene:'exterior'|'apartamento'){setActive(scene);setOpened(true);const url=new URL(location.href);url.searchParams.set('cena',scene);history.pushState(null,'',url);requestAnimationFrame(()=>experience.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}
 async function share(){try{const url=new URL(location.href);url.searchParams.set('cena',active);await navigator.clipboard.writeText(url.href);setNotice('Link desta experiência copiado.');}catch{setNotice('Copie o endereço desta página para compartilhar.');}}
 const closeViewer=()=>{setOpened(false);const url=new URL(location.href);url.searchParams.delete('cena');history.replaceState(null,'',url);};
 return <main className="botanique">
  <header className="b-header"><a className="b-brand" href="/" aria-label="EME Spatial, início"><span className="b-brand-mark">S</span><span>EME <b>SPATIAL</b></span></a><a className="b-project-wordmark" href="#inicio"><img src="/assets/botanique/brand/botanique-logo-white.svg" alt="Botanique Home Resort"/></a><nav aria-label="Navegação da apresentação"><a href="#experiencia">Experiência</a><a href="#imagens">Imagens</a><button onClick={()=>explore('apartamento')} className="b-header-cta">Visitar apartamento <ArrowUpRight size={15}/></button></nav></header>
  <section className="b-hero" id="inicio">
   {hero?<img className="b-hero-image" src={hero.url} alt={hero.title} fetchPriority="high"/>:<div className="b-hero-placeholder" aria-hidden="true"><TreePine/><span>BOTANIQUE</span></div>}
   <div className="b-hero-shade"/><div className="b-hero-copy"><span className="b-eyebrow">PASSO FUNDO · SÃO CRISTÓVÃO</span><h1>Uma nova forma<br/>de conhecer<br/><em>o Botanique.</em></h1><p>Da natureza ao seu espaço de viver.<br/>Explore uma demonstração criada para este empreendimento.</p><div className="b-actions"><button className="b-button b-button-light" onClick={()=>explore('exterior')}><Box size={17}/>Explorar em 3D<ArrowUpRight size={17}/></button><a className="b-hero-link" href="#imagens">Ver apresentação <ArrowDown size={16}/></a></div></div>
   <div className="b-hero-bottom"><span>{hero?heroLabel:'PRÉ-APRESENTAÇÃO · EME SPATIAL'}</span><a href="#experiencia">Uma visita. Muitas possibilidades.<ArrowDown size={14}/></a></div>
  </section>
  <section className="b-intro b-section"><div><span className="b-eyebrow">UM PROJETO PARA EXPLORAR</span><h2>Veja o conjunto.<br/><em>Sinta os detalhes.</em></h2></div><div className="b-intro-copy"><p>O encontro entre o edifício, os espaços de convivência e a paisagem é o ponto de partida desta experiência.</p><p>Conheça o empreendimento por diferentes perspectivas e entre em um apartamento de estudo. A mesma base 3D conecta a visita aos novos materiais visuais.</p><div className="b-meta"><span><Leaf size={17}/>Paisagem e convivência</span><span><Box size={17}/>Apartamento de estudo</span><span><Sun size={17}/>Luz e materiais</span></div></div></section>
  <section className="b-experience b-section" id="experiencia" ref={experience}>
   <div className="b-section-head"><div><span className="b-eyebrow">VOCÊ ESCOLHE A PERSPECTIVA</span><h2>Entre na experiência.</h2></div><p>O conjunto e o apartamento abrem separadamente<br/>para uma navegação mais leve.</p></div>
   <div className="b-scene-tabs" role="group" aria-label="Escolher cenário"><button aria-pressed={active==='exterior'} onClick={()=>explore('exterior')}><TreePine size={17}/><span>Empreendimento<small>Fachada, implantação e lazer</small></span><ChevronRight size={16}/></button><button aria-pressed={active==='apartamento'} onClick={()=>explore('apartamento')}><Box size={17}/><span>Apartamento<small>Final 1 · 2 dormitórios com suíte</small></span><ChevronRight size={16}/></button></div>
   {active==='apartamento'&&<p className="b-unit-context">Final 1 · 2 dormitórios com suíte <span>55,55 m² informados na planta comercial. Reconstrução em escala estimada.</span></p>}
   {opened?<div className="b-viewer-shell"><div className="b-viewer-caption"><span><i/>EXPERIÊNCIA INTERATIVA · {active==='exterior'?'EMPREENDIMENTO':'APARTAMENTO DE ESTUDO'}</span><button onClick={closeViewer}><X size={15}/>Fechar 3D</button></div>{loading?<div className="b-load" role="status"><span className="b-spinner"/>Preparando a experiência…</div>:manifest.scenes[active]?<Suspense fallback={<div className="b-load" role="status"><span className="b-spinner"/>Preparando o visualizador…</div>}><Viewer key={active} kind={active} definition={manifest.scenes[active]!} onEnterApartment={()=>explore('apartamento')}/></Suspense>:<div className="b-load b-unavailable" role="status"><ImageIcon size={28}/><h3>Este cenário está em preparação.</h3><p>{failure||'As imagens disponíveis podem ser exploradas na galeria abaixo.'}</p><a href="#imagens" className="b-button">Ver imagens<ArrowDown size={15}/></a></div>}</div>:<div className="b-launch"><div><span className="b-eyebrow">SUA PRÓXIMA VISITA COMEÇA AQUI</span><h3>Conheça o espaço<br/>no seu próprio ritmo.</h3><p>Escolha uma vista, aproxime os detalhes e descubra o apartamento.</p><button className="b-button" onClick={()=>explore(active)}><Play size={16}/>Iniciar experiência</button></div><div className="b-launch-visual">{hero?<img src={hero.url} alt="Prévia do empreendimento" loading="lazy"/>:<TreePine size={90} strokeWidth={.5}/>}<button aria-label="Iniciar experiência 3D" onClick={()=>explore(active)}><Play size={27} fill="currentColor"/></button></div></div>}
   <div className="b-experience-note"><span>{manifest.disclaimer}</span><button onClick={share}><Share2 size={14}/>Compartilhar visita</button></div>{notice&&<p className="b-inline-notice" role="status"><Check size={14}/>{notice}</p>}
  </section>
  {manifest.video&&<section className="b-film b-section" aria-label="Filme da experiência"><div className="b-section-head"><div><span className="b-eyebrow">UMA PRÉVIA DA VISITA</span><h2>O espaço responde<br/><em>às suas escolhas.</em></h2></div><p>Da planta ao ambiente.<br/>Veja a navegação e as escolhas em ação.</p></div><video controls playsInline preload="none" poster={manifest.video.poster} src={manifest.video.url} aria-label="Demonstração da navegação, móveis e luzes do Botanique"/><p className="b-film-caption">Captura da experiência interativa EME Spatial.</p></section>}
  <section className="b-gallery b-section" id="imagens"><div className="b-section-head"><div><span className="b-eyebrow">ARQUITETURA, LUZ E NATUREZA</span><h2>O projeto em imagens.</h2></div><p>Perspectivas para conhecer os espaços.<br/>Cada imagem identifica sua origem.</p></div>{manifest.images.length?<div className="b-image-grid">{manifest.images.map((image,index)=><button className={'b-gallery-image '+(index===0?'b-gallery-featured':'')} key={image.url} onClick={()=>setLightbox(index)} aria-label={'Ampliar '+image.title}><div><img src={image.url} alt={image.title} loading="lazy"/><span className="b-image-kind">{image.kind==='render'?'PRODUÇÃO EME SPATIAL':'REFERÊNCIA DO EMPREENDIMENTO'}</span><span className="b-expand"><Expand size={16}/></span></div><p>{image.title}<ArrowUpRight size={16}/></p>{image.credit&&<small>{image.credit}</small>}</button>)}</div>:<div className="b-empty-gallery"><ImageIcon size={26}/><p>{loading?'Organizando o material visual…':'As primeiras imagens estão em preparação.'}</p>{failure&&<small>{failure}</small>}</div>}</section>
  <section className="b-possibilities"><div className="b-section"><span className="b-eyebrow">DO MESMO PROJETO, DIFERENTES ENTREGAS</span><h2>Uma apresentação<br/>que continua <em>depois da reunião.</em></h2><div className="b-possibility-grid"><article><Box/><span>01</span><h3>Exploração do espaço</h3><p>Conjunto, pontos de vista e visita aos ambientes do apartamento de estudo.</p></article><article><Sun/><span>02</span><h3>Escolhas visuais</h3><p>Compare modelos de sofá e cadeiras, combine acabamentos e escolha entre luz quente, neutra e fria. Salve sua ambientação.</p></article><article><ImageIcon/><span>03</span><h3>Material de apresentação</h3><p>Imagens, apresentação e uma prévia em vídeo acompanham a experiência para continuar a conversa depois da reunião.</p></article></div></div></section>
  <footer className="b-footer"><div><span className="b-brand">EME <b>SPATIAL</b></span><p>Pré-apresentação · Botanique Home Resort</p><small>{manifest.disclaimer} As opções de decoração são propostas demonstrativas e não especificações de entrega da construtora.</small></div><div className="b-footer-links"><div className="b-project-partners" aria-label="Realização do empreendimento"><span>EMPREENDIMENTO</span><img src="/assets/botanique/brand/bbdr-logo-white.png" alt="BBDR Construtora"/><img src="/assets/botanique/brand/engemaffer-logo-white.png" alt="Engemaffer Engenharia e Construções"/></div>{manifest.presentation&&<a className="b-button" href={manifest.presentation.url} download><Download size={15}/>{manifest.presentation.label||'Baixar apresentação'}</a>}<a href="/">Conheça o EME Spatial<ArrowUpRight size={16}/></a></div></footer>
  {lightbox!==null&&manifest.images[lightbox]&&<div className="b-lightbox" role="dialog" aria-modal="true" aria-label={manifest.images[lightbox].title} onClick={()=>setLightbox(null)}><button ref={closeImage} className="b-lightbox-close" aria-label="Fechar imagem" onClick={()=>setLightbox(null)}><X/></button><button className="b-lightbox-prev" aria-label="Imagem anterior" onClick={e=>{e.stopPropagation();setLightbox((lightbox-1+manifest.images.length)%manifest.images.length);}}><ArrowLeft/></button><figure onClick={e=>e.stopPropagation()}><img src={manifest.images[lightbox].url} alt={manifest.images[lightbox].title}/><figcaption><strong>{manifest.images[lightbox].title}</strong><span>{manifest.images[lightbox].kind==='render'?'Produção EME Spatial':'Referência do empreendimento'}{manifest.images[lightbox].credit?' · '+manifest.images[lightbox].credit:''}</span></figcaption></figure><button className="b-lightbox-next" aria-label="Próxima imagem" onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%manifest.images.length);}}><ArrowRight/></button></div>}
 </main>;
}
