import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {createBotaniqueLighting,formatSolarHour,botaniqueSun} from './botaniqueLighting';
import {botaniquePalettes as palettes,isBotaniquePalette} from './botaniquePalettes';
import {createBotaniqueNavigator} from './botaniqueNavigation';
import {createBotaniquePlanContext} from './botaniquePlanContext';
import type {BotaniquePalette} from './botaniquePalettes';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {applyFurnitureVariant,isFurnitureVariant,isFurnitureGroup,isFurnitureChoice,isLightTemperature,temperatureColor,defaultFurniture,furnitureGroups} from './botaniqueFurniture';
import BotaniqueFurnitureCatalog from './BotaniqueFurnitureCatalog';
import BotaniqueMobileControls from './BotaniqueMobileControls';
import BotaniqueRecorder,{isBotaniqueRecording} from './BotaniqueRecorder';
import {stepBotaniquePlayer} from './botaniquePlayer';
import {createBotaniqueVisualRefinement} from './botaniqueVisualRefinement';
import type {FurnitureGroup,FurnitureVariant,FurnitureSelections,LightTemperature} from './botaniqueFurniture';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {ArrowRight,Check,Expand,Home,Layers,LoaderCircle,Maximize2,Minus,Footprints,Pause,Play,Plus,RotateCcw,Save,Sun,X} from 'lucide-react';
import type {BotaniqueScene,BotaniqueVector,BotaniqueView} from './BotaniquePage';

type Quality='auto'|'light'|'high';
type Api={move:(x:number,y:number)=>void;redraw:()=>void;furniture:(group:FurnitureGroup,variant:FurnitureVariant)=>void;temperature:(value:LightTemperature)=>void;view:(view:BotaniqueView,room?:boolean)=>void;home:()=>void;top:(detail?:boolean)=>void;zoom:(direction:number)=>void;light:(hour:number)=>void;indoor:(value:number)=>void;palette:(palette:BotaniquePalette)=>void;finish:(kind:'wood'|'fabric',value:string)=>void;walk:(enabled:boolean)=>void;quality:(quality:Quality)=>void;tour:(enabled:boolean)=>void};
const emptyViews:BotaniqueView[]=[];
const tuple=(v:BotaniqueVector)=>new T.Vector3(...v);
class BotaniqueOcclusion extends GTAOPass {
 override setSize(width:number,height:number){super.setSize(Math.max(1,Math.round(width*.6)),Math.max(1,Math.round(height*.6)));}
 override render(renderer:T.WebGLRenderer,writeBuffer:T.WebGLRenderTarget,readBuffer:T.WebGLRenderTarget,delta:number,mask:boolean){
  const hidden:T.Mesh[]=[];this.scene.traverse(object=>{if(!(object instanceof T.Mesh)||!object.visible)return;const materials=Array.isArray(object.material)?object.material:[object.material];if(materials.every(m=>m.alphaTest>0||(m.transparent&&(m.opacity<.95||('map' in m&&!!m.map)||('alphaMap' in m&&!!m.alphaMap))))){hidden.push(object);object.visible=false;}});
  try{super.render(renderer,writeBuffer,readBuffer,delta,mask);}finally{hidden.forEach(o=>o.visible=true);}
 }
}
export default function BotaniqueViewer({kind,definition,onEnterApartment}:{kind:'exterior'|'apartamento';definition:BotaniqueScene;onEnterApartment:()=>void}){
 const host=useRef<HTMLDivElement>(null),container=useRef<HTMLDivElement>(null),api=useRef<Api|null>(null);
 const planLabels=useRef(new Map<string,HTMLElement>());
 const [planActive,setPlanActive]=useState(false),[planDetail,setPlanDetail]=useState(false),[materialsOpen,setMaterialsOpen]=useState(false);
 const expandedRef=useRef(false);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[view,setView]=useState(kind==='apartamento'?(definition.views[0]?.label||'Apartamento de estudo'):'Visão inicial'),[hour,setHour]=useState(16.5),[indoor,setIndoor]=useState(.65),[palette,setPalette]=useState<BotaniquePalette>('salvia'),[walking,setWalking]=useState(kind==='apartamento'),[walkHint,setWalkHint]=useState(''),[woodTone,setWoodTone]=useState('composicao'),[fabricTone,setFabricTone]=useState('composicao'),[quality,setQuality]=useState<Quality>('auto'),[saved,setSaved]=useState(''),[tour,setTour]=useState(false),[full,setFull]=useState(false),[fade,setFade]=useState(false),[materialAvailable,setMaterialAvailable]=useState(false),[roomMode,setRoomMode]=useState(kind==='apartamento'),[roomsOpen,setRoomsOpen]=useState(false);
 useEffect(()=>{if(!full)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!document.fullscreenElement&&!container.current?.querySelector('.bfc')){setFull(false);expandedRef.current=false;}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);};},[full]);
 const [selections,setSelections]=useState<FurnitureSelections>({...defaultFurniture}),[temperature,setTemperature]=useState<LightTemperature>(3000);
 const [catalogOpen,setCatalogOpen]=useState(false),[catalogGroup,setCatalogGroup]=useState<FurnitureGroup>('sofa'),[furnitureObjects,setFurnitureObjects]=useState<T.Object3D[]>([]);
 function openCatalog(group:FurnitureGroup='sofa'){setCatalogGroup(group);setCatalogOpen(true);setRoomsOpen(false);const panel=container.current?.querySelector<HTMLDetailsElement>('.b-materials');if(panel)panel.open=false;}
 const rooms=definition.rooms||emptyViews,views=definition.views||emptyViews,apartment=kind==='apartamento';
 const places=apartment?rooms:definition.walkEntries||emptyViews;
 useEffect(()=>{
  const mount=host.current!;let renderer:T.WebGLRenderer;
  try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'default'});}catch{setError('Leitura 3D indisponível neste equipamento. As imagens da apresentação continuam disponíveis.');return;}
  let disposed=false,frame=0,last=0,visible=true,loaded=false,performanceSamples=0,performanceSum=0,lightProfile=(window.navigator.hardwareConcurrency||4)<=4,qualityMode:Quality='auto';
  let visualRefinement:ReturnType<typeof createBotaniqueVisualRefinement>|undefined,liveRequested=false;
  const abort=new AbortController(),resources=new Set<{dispose:()=>void}>(),timers=new Set<ReturnType<typeof setTimeout>>();
  const later=(fn:()=>void,time:number)=>{const timer=setTimeout(()=>{timers.delete(timer);if(!disposed)fn();},time);timers.add(timer);return timer;};
  const own=<A extends {dispose:()=>void}>(resource:A)=>{resources.add(resource);return resource;};
  renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.shadowMap.autoUpdate=false;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label',apartment?'Apartamento Botanique em 3D. Clique no piso para caminhar e arraste para olhar.':'Empreendimento Botanique em 3D. Arraste para girar ou ative Passear para caminhar.');mount.appendChild(renderer.domElement);
  const scene=new T.Scene();scene.background=new T.Color('#dce3dd');
  const planContext=apartment?createBotaniquePlanContext({rooms,floor:definition.floorContext}):undefined;
  if(planContext)scene.add(planContext.group);
  const camera=new T.PerspectiveCamera(apartment?58:43,1,.06,apartment?160:650),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=apartment?2:8;controls.maxDistance=apartment?28:260;controls.maxPolarAngle=Math.PI*.49;controls.screenSpacePanning=true;controls.target.copy(tuple(definition.camera.target));camera.position.copy(tuple(definition.camera.position));controls.update();
  if(!apartment)scene.fog=new T.Fog('#dce3dd',145,430);
  const daylight=createBotaniqueLighting(scene,renderer,apartment,()=>draw(),definition.modeledLights),sun=daylight.sun;
  let post:{composer:EffectComposer;render:RenderPass;ao:BotaniqueOcclusion;bloom:UnrealBloomPass;output:OutputPass;width:number;height:number;ratio:number}|undefined,postFailed=false;
  let root:T.Group|undefined,inRoom=apartment,topMode=false,solarHour=16.5,indoorPower=.65,tourOn=false,tourIndex=0,tourAt=0,yaw=0,pitch=0,roomTimer:ReturnType<typeof setTimeout>|undefined;
  let planClose=false,lightTemperature:LightTemperature=3000;
  const variantObjects:T.Object3D[]=[],selectedFurniture: FurnitureSelections={...defaultFurniture};
  controls.enabled=!apartment;
  let flight:{start:number;duration:number;from:T.Vector3;to:T.Vector3;fromLook:T.Vector3;toLook:T.Vector3}|null=null;
  const woods:T.MeshStandardMaterial[]=[],originalColors=new Map<T.MeshStandardMaterial,T.Color>();
  const roof:T.Object3D[]=[],accent:T.MeshStandardMaterial[]=[],fabric:T.MeshStandardMaterial[]=[],emissives:{material:T.MeshStandardMaterial;intensity:number;color:T.Color}[]=[],lamps:{light:T.Light;intensity:number}[]=[];
  const walkNavigator=definition.navigation?createBotaniqueNavigator(definition.navigation,{radius:apartment?.22:.35,eyeHeight:1.6,gridSize:apartment?.13:.48,maxExpandedNodes:18000}):null;
  let walkRoute:T.Vector3[]=[];let walkIndex=0,walkTime=0,renderClock=0,previousContinuous=false;
  const movement={x:0,y:0};let moveAt=0;
  function moveInput(x:number,y:number){const wasMoving=!!(movement.x||movement.y);movement.x=Number.isFinite(x)?T.MathUtils.clamp(x,-1,1):0;movement.y=Number.isFinite(y)?T.MathUtils.clamp(y,-1,1):0;if(movement.x||movement.y){stopWalk();cancelTour();if(!wasMoving)moveAt=performance.now();draw();}}
  const marker=new T.Mesh(own(new T.RingGeometry(.12,.18,36)),own(new T.MeshBasicMaterial({color:'#f8f1ce',transparent:true,opacity:.85,depthWrite:false,side:T.DoubleSide})));marker.rotation.x=-Math.PI/2;marker.visible=false;scene.add(marker);
  function stopWalk(){walkRoute=[];walkIndex=0;marker.visible=false;}
  function hint(message:string){setWalkHint(message);later(()=>setWalkHint(''),3500);}
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  const draw=()=>{if(disposed||document.hidden||(!visible&&!liveRequested)||frame)return;frame=requestAnimationFrame(render);};
  function profile(){const recording=isBotaniqueRecording(),low=!recording&&(qualityMode==='light'||(qualityMode==='auto'&&lightProfile)),pixels=low?900000:1800000;daylight.setQuality(low);renderer.setPixelRatio(recording?Math.min(2.5,Math.max(1920/Math.max(1,mount.clientWidth),1080/Math.max(1,mount.clientHeight))):Math.min(devicePixelRatio,low?1:1.5,Math.sqrt(pixels/Math.max(1,mount.clientWidth*mount.clientHeight))));renderer.setSize(mount.clientWidth,mount.clientHeight);const size=qualityMode==='high'?2048:1024;if(sun.shadow.mapSize.x!==size){sun.shadow.mapSize.setScalar(size);sun.shadow.map?.dispose();sun.shadow.map=null;}renderer.shadowMap.needsUpdate=true;draw();}
  async function prepareViewPrograms(){
   if(!apartment)return;
   const started=performance.now();mount.dataset.shaders='preparing';
   // The loading overlay keeps painting while the driver prepares programs.
   // Wait for the debounced sky environment before choosing their shader keys.
   await new Promise<void>(resolve=>setTimeout(resolve,240));if(disposed)return;
   daylight.focus(camera.position,inRoom);scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);
   const linearTarget=new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType});
   try{
    // Interior postprocessing uses a linear target; the floor plan/mobile path
    // renders directly with tone mapping. Warm both before making them clickable.
    for(const target of [linearTarget,null]){
     if(disposed)return;
     const previous=renderer.getRenderTarget(),face=renderer.getActiveCubeFace(),level=renderer.getActiveMipmapLevel();let compilation:Promise<unknown>;
     try{renderer.setRenderTarget(target);compilation=renderer.compileAsync(scene,camera);}
     finally{renderer.setRenderTarget(previous,face,level);}
     await compilation;
    }
    mount.dataset.shaderPreparationMs=String(Math.round(performance.now()-started));mount.dataset.shaders='ready';
   }finally{linearTarget.dispose();}
  }
  function look(){camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);}
  function syncLook(target:T.Vector3){const direction=target.clone().sub(camera.position).normalize();yaw=Math.atan2(-direction.x,-direction.z);pitch=Math.asin(T.MathUtils.clamp(direction.y,-1,1));look();}
  function cancelTour(){tourOn=false;setTour(false);}
  function select(next:BotaniqueView,room=false,automatic=false){
   movement.x=movement.y=0;stopWalk();setWalkHint('');setWalking(room);if(!automatic)cancelTour();if(roomTimer){clearTimeout(roomTimer);timers.delete(roomTimer);roomTimer=undefined;}
   flight=null;topMode=false;planContext?.setVisible(false);setPlanActive(false);daylight.setPlanContext(null);controls.minDistance=apartment?2:8;controls.maxDistance=apartment?28:260;roof.forEach(o=>o.visible=!isFurnitureGroup(o.userData.variantGroup)||o.userData.variantId===selectedFurniture[o.userData.variantGroup]);setView(next.label);setRoomMode(room);renderer.shadowMap.needsUpdate=true;
   const destination=tuple(next.position),target=tuple(next.target),wasRoom=inRoom;inRoom=room;controls.enabled=!room;
   const position=()=>{camera.position.copy(destination);controls.target.copy(target);camera.fov=room?58:apartment?53:43;camera.updateProjectionMatrix();if(room)syncLook(target);else controls.update();draw();};
   if(room||wasRoom){setFade(true);roomTimer=later(()=>{position();setFade(false);roomTimer=undefined;},reduced.matches?0:160);}
   else if(reduced.matches){position();}else{flight={start:performance.now(),duration:automatic?3800:1000,from:camera.position.clone(),to:destination,fromLook:controls.target.clone(),toLook:target};draw();}
  }
  const initial:BotaniqueView={id:'initial',label:apartment?(views[0]?.label||'Apartamento de estudo'):'Visão inicial',...definition.camera};
  function plan(detail=false){
   setCatalogOpen(false);setMaterialsOpen(false);movement.x=movement.y=0;
   if(!planContext)return;
   stopWalk();setWalking(false);cancelTour();if(roomTimer){clearTimeout(roomTimer);timers.delete(roomTimer);roomTimer=undefined;}
   setFade(false);flight=null;inRoom=false;topMode=true;planClose=detail;controls.enabled=true;controls.minDistance=detail?5:12;controls.maxDistance=140;
   setRoomMode(false);setRoomsOpen(false);setPlanActive(true);setPlanDetail(detail);setView('Planta 3D');roof.forEach(o=>o.visible=false);planContext.setVisible(true);
   const next=detail?planContext.unitCamera:planContext.camera;controls.target.fromArray(next.target);camera.position.fromArray(next.position);
   // Keep the full floor readable on a narrow phone without cropping the wings.
   if(!detail&&camera.aspect<1.35)camera.position.sub(controls.target).multiplyScalar(Math.min(2.15,1.35/camera.aspect)).add(controls.target);
   if(detail&&camera.aspect<.95)camera.position.sub(controls.target).multiplyScalar(Math.sqrt(.95/camera.aspect)).add(controls.target);
   camera.fov=52;camera.updateProjectionMatrix();controls.update();daylight.setPlanContext({center:(detail?planContext.unitBounds:planContext.floorBounds).getCenter(new T.Vector3()),span:detail?11:31});
   mount.dataset.floorContext=planContext.floorContext.label;renderer.shadowMap.needsUpdate=true;draw();later(draw,40);
  }
  function planPick(event:PointerEvent){
   if(!topMode||!planContext)return;
   const rect=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster(),point=new T.Vector3();
   ray.setFromCamera(new T.Vector2((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1),camera);
   // In a cutaway, the full-height front wall must not steal a click aimed at
   // the room behind it. Floors and low furniture are the selectable surfaces.
   const surface=root?ray.intersectObject(root,true).find(hit=>{let node:T.Object3D|null=hit.object;while(node){if(!node.visible)return false;node=node.parent;}return hit.point.y>=-.08&&hit.point.y<=1.4&&!!hit.face&&hit.face.normal.clone().transformDirection(hit.object.matrixWorld).y>.65;}):undefined;
   if(surface)point.copy(surface.point);else if(!ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-.035),point))return;
   const room=planContext.pickRoom(point),destination=rooms.find(r=>r.id===room?.id);
   if(destination)select(destination,true);else hint('O apartamento destacado é a Final 1. Aproxime para escolher um ambiente.');
  }
  function lighting(value:number){
   solarHour=value;setHour(value);daylight.setHour(value);const night=1-botaniqueSun(value).day;
   emissives.forEach(({material,intensity,color})=>{
    if(apartment){material.emissive.set(temperatureColor[lightTemperature]).multiplyScalar(Math.max(color.r,color.g,color.b));material.emissiveIntensity=Math.max(.1,intensity)*indoorPower*(.7+.45*night);}
    else{material.emissive.copy(color);const window=material.name.startsWith('B_WINDOW_glow');if(window)material.emissive.multiplyScalar(1/Math.max(.001,color.r,color.g,color.b));material.emissiveIntensity=window?.025+.8*night:Math.max(.35,intensity)*(.08+1.6*night);}
   });
   lamps.forEach(({light,intensity})=>light.intensity=intensity*(apartment?indoorPower:night)*(.55+.45*night));mount.dataset.night=night.toFixed(2);draw();
  }
  function changeTemperature(value:LightTemperature){if(!isLightTemperature(value))return;lightTemperature=value;setTemperature(value);daylight.setTemperature(value);mount.dataset.lightTemperature=String(value);lighting(solarHour);}
  function furniture(group:FurnitureGroup,variant:FurnitureVariant){if(!isFurnitureChoice(group,variant)||!applyFurnitureVariant(variantObjects,group,variant))return;selectedFurniture[group]=variant;setSelections(previous=>({...previous,[group]:variant}));mount.dataset[group]=variant;renderer.shadowMap.needsUpdate=true;daylight.refreshInterior();draw();}
  function changePalette(value:BotaniquePalette){setPalette(value);const p=palettes[value];accent.forEach(m=>m.color.set(p.accent));fabric.forEach(m=>m.color.copy(originalColors.get(m)!).multiply(new T.Color(p.fabric)));woods.forEach(m=>m.color.copy(originalColors.get(m)!).multiply(new T.Color(p.wood)));setWoodTone('composicao');setFabricTone('composicao');daylight.refreshInterior();draw();}
  function finish(kind:'wood'|'fabric',value:string){const colors=kind==='wood'?{natural:'#fff6e9',mel:'#dfb787',nogueira:'#9d816a',clara:'#fffefa'}:{linho:'#fff2dc',perola:'#ffffff',oliva:'#a4ae88',terracota:'#bc8167'};const color=colors[value as keyof typeof colors];if(typeof color!=='string')return;(kind==='wood'?woods:fabric).forEach(m=>m.color.copy(originalColors.get(m)!).multiply(new T.Color(color)));if(kind==='wood')setWoodTone(value);else setFabricTone(value);daylight.refreshInterior();draw();}
  function walkingMode(enabled:boolean){movement.x=movement.y=0;stopWalk();cancelTour();if(!enabled){inRoom=false;setWalking(false);setRoomMode(false);controls.target.copy(camera.position).add(camera.getWorldDirection(new T.Vector3()).multiplyScalar(3));controls.enabled=true;controls.update();draw();return;}if(!walkNavigator){hint('A caminhada deste cenário está sendo preparada.');return;}const floor=camera.position.clone().add(new T.Vector3(0,-walkNavigator.eyeHeight,0)),standing=walkNavigator.projectToFloor(floor,.22);if(!inRoom||!standing){const entry=(!apartment?definition.walkEntries?.find(e=>e.id==='piscina'):undefined)||definition.walkEntries?.[0];if(!entry){hint('Escolha um ambiente para começar o passeio.');return;}select(entry,true);}else{inRoom=true;controls.enabled=false;setWalking(true);setRoomMode(true);}hint('Clique no piso livre para caminhar. Arraste para olhar.');draw();}
  function walkTo(event:PointerEvent){
   if(!inRoom||!walkNavigator||!root)return;
   const rect=renderer.domElement.getBoundingClientRect(),ndc=new T.Vector2((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1),ray=new T.Raycaster();ray.setFromCamera(ndc,camera);
   const hit=ray.intersectObject(root,true).find(h=>{let object:T.Object3D|null=h.object;while(object){if(!object.visible)return false;object=object.parent;}if(h.object instanceof T.Mesh){const materials=Array.isArray(h.object.material)?h.object.material:[h.object.material];if(materials.every(m=>m.transparent&&m.opacity<.65))return false;}return true;});
   if(apartment&&hit&&isFurnitureGroup(hit.object.userData.variantGroup)){stopWalk();cancelTour();openCatalog(hit.object.userData.variantGroup);return;}
   if(!hit||!hit.face||hit.face.normal.clone().transformDirection(hit.object.matrixWorld).y<.75){hint('Clique em uma área livre do piso.');return;}
   const target=walkNavigator.projectToFloor(hit.point,.11);if(!target){hint('Esse ponto está ocupado. Escolha uma área livre do piso.');return;}
   const route=walkNavigator.planRoute(camera.position,target);if(!route.ok){hint(route.reason==='invalid-start'?'Escolha uma vista de ambiente para iniciar a caminhada.':'Não há passagem livre até esse ponto. Tente um ponto mais próximo.');mount.dataset.walkResult=route.reason;return;}
   flight=null;cancelTour();walkRoute=route.points;walkIndex=0;walkTime=performance.now();setView('Passeio livre');setWalkHint('');marker.position.copy(target).y+=.018;marker.visible=true;mount.dataset.walkResult='moving';draw();
  }
  function render(now:number){frame=0;if(disposed||document.hidden||(!visible&&!liveRequested)||!loaded)return;liveRequested=false;const active=!!(flight||tourOn||walkRoute.length||pointer?.dragged||movement.x||movement.y);const tick=1000/60,elapsed=now-renderClock;if(active&&elapsed<tick){draw();return;}renderClock=active?now-elapsed%tick:now;const start=performance.now(),frameInterval=last?now-last:16.7,continuedMotion=active&&previousContinuous;
   if(walkRoute.length){let remaining=Math.min(.06,Math.max(0,(now-walkTime)/1000))*(apartment?1.1:1.75);walkTime=now;while(remaining>0&&walkIndex<walkRoute.length){const next=walkRoute[walkIndex],distance=camera.position.distanceTo(next);if(distance<=remaining){camera.position.copy(next);remaining-=distance;walkIndex++;}else{camera.position.lerp(next,remaining/distance);remaining=0;}}if(walkIndex>=walkRoute.length){stopWalk();mount.dataset.walkResult='arrived';}look();}
   if(inRoom&&walkNavigator&&(movement.x||movement.y)){camera.position.copy(stepBotaniquePlayer(walkNavigator,camera.position,yaw,movement,(now-moveAt)/1000,apartment?1.1:1.8));moveAt=now;look();}
   daylight.focus(camera.position,inRoom);mount.dataset.camera=JSON.stringify(camera.position.toArray().map(n=>Math.round(n*1000)/1000));
   if(flight){const t=T.MathUtils.clamp((now-flight.start)/flight.duration,0,1),e=t*t*(3-2*t);camera.position.lerpVectors(flight.from,flight.to,e);controls.target.lerpVectors(flight.fromLook,flight.toLook,e);controls.update();if(t>=1)flight=null;}
   if(tourOn){const options=apartment&&rooms.length?rooms:views;if(options.length&&now-tourAt>6500){tourAt=now;select(options[tourIndex++%options.length],apartment&&rooms.length>0,true);}if(inRoom&&!reduced.matches){camera.rotation.z=Math.sin((now-tourAt)/6500*Math.PI)*.002;}}
   mount.dataset.planMode=topMode?(planClose?'unit':'floor'):'off';
   if(topMode&&planContext){
    mount.dataset.planTarget=JSON.stringify(controls.target.toArray());mount.dataset.planFov=String(camera.fov);
    camera.updateMatrixWorld();
    const placeLabel=(id:string,position:BotaniqueVector,show:boolean)=>{const label=planLabels.current.get(id);if(!label)return;const p=tuple(position).project(camera);const inFrame=show&&p.z>-1&&p.z<1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.92;label.style.visibility=inFrame?'visible':'hidden';if(inFrame){label.style.left=`${(p.x+1)*mount.clientWidth/2}px`;label.style.top=`${(1-p.y)*mount.clientHeight/2}px`;}};
    planContext.units.forEach(unit=>placeLabel(unit.id,unit.labelPosition,!planClose));
    planContext.roomHotspots.filter(r=>r.primary).forEach(room=>placeLabel(room.id,room.position,planClose));
   }
   const contactShading=loaded&&(apartment?inRoom:solarHour>=18.5)&&!postFailed&&mount.clientWidth>=850&&qualityMode!=='light'&&!(qualityMode==='auto'&&lightProfile);
   if(contactShading){try{if(!post){const composer=new EffectComposer(renderer),renderPass=new RenderPass(scene,camera),ao=new BotaniqueOcclusion(scene,camera),bloom=new UnrealBloomPass(new T.Vector2(1,1),.16,.35,1.15),output=new OutputPass();ao.updateGtaoMaterial({radius:.32,thickness:.13,distanceFallOff:.8,scale:.8,samples:8});ao.updatePdMaterial({radius:3,samples:9});ao.blendIntensity=.58;composer.renderTarget1.samples=2;composer.renderTarget2.samples=2;composer.addPass(renderPass);composer.addPass(ao);composer.addPass(bloom);composer.addPass(output);post={composer,render:renderPass,ao,bloom,output,width:0,height:0,ratio:0};later(draw,100);later(draw,300);}post.ao.enabled=apartment&&inRoom;const size=renderer.getSize(new T.Vector2()),ratio=renderer.getPixelRatio();if(size.x!==post.width||size.y!==post.height||ratio!==post.ratio){post.width=size.x;post.height=size.y;post.ratio=ratio;post.composer.setPixelRatio(ratio);post.composer.setSize(size.x,size.y);}renderer.info.autoReset=false;renderer.info.reset();try{post.composer.render();}finally{renderer.info.autoReset=true;}}catch{postFailed=true;renderer.render(scene,camera);}}else renderer.render(scene,camera);
   document.dispatchEvent(new CustomEvent('b-live-rendered',{detail:{canvas:renderer.domElement}}));
   last=now;mount.dataset.contactShadows=String(apartment&&contactShading&&!postFailed);mount.dataset.drawCalls=String(renderer.info.render.calls);mount.dataset.triangles=String(renderer.info.render.triangles);mount.dataset.frame=String(Number(mount.dataset.frame||0)+1);mount.dataset.scene=kind;mount.dataset.quality=qualityMode==='auto'?(lightProfile?'leve':'equilibrada'):qualityMode;
   if(qualityMode==='auto'&&!lightProfile&&continuedMotion){performanceSum+=Math.max(performance.now()-start,frameInterval);performanceSamples++;const average=performanceSum/performanceSamples,severelyLimited=performanceSamples>=4&&average>120,limited=performanceSamples>=8&&average>55;if(severelyLimited||limited||(performanceSamples>=40&&average>34)){lightProfile=true;profile();}if(performanceSamples>=40){performanceSamples=0;performanceSum=0;}}
   previousContinuous=active;if(flight||tourOn||walkRoute.length||pointer?.dragged||movement.x||movement.y)draw();
  }
  const draco=new DRACOLoader();draco.setDecoderPath('/assets/draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);
  fetch(definition.url,{signal:abort.signal}).then(response=>{if(!response.ok)throw Error('O modelo desta vista não está disponível. A galeria permanece acessível.');return response.arrayBuffer();}).then(buffer=>loader.parseAsync(buffer,definition.url.slice(0,definition.url.lastIndexOf('/')+1))).then(async gltf=>{
   const asset=gltf.scene;asset.traverse(o=>{if(o instanceof T.Mesh){own(o.geometry);const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{own(m);for(const v of Object.values(m))if(v instanceof T.Texture)own(v);});}});if(disposed){resources.forEach(r=>r.dispose());return;}
   root=asset;visualRefinement=createBotaniqueVisualRefinement(asset,{apartment,maxAnisotropy:renderer.capabilities.getMaxAnisotropy()});mount.dataset.visualRevision=String(visualRefinement.stats.revision);asset.traverse(o=>{if(o.userData.variantGroup){variantObjects.push(o);o.visible=o.userData.variantId==='contemporaneo';}if(o.name.startsWith('B_UNIT_ROOF')||o.name.startsWith('B_UNIT_DOWNLIGHT')||['ceiling-light','hanging-light','context','curtain-high'].includes(o.userData.role)||o.userData.context_only||o.userData.exclude_from_bounds)roof.push(o);if(o instanceof T.Light)lamps.push({light:o,intensity:o.intensity});if(o instanceof T.Mesh){o.castShadow=!o.userData.noShadow;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(m instanceof T.MeshStandardMaterial){if(!m.transparent&&m.alphaTest===0)m.shadowSide=T.BackSide;if(!originalColors.has(m))originalColors.set(m,m.color.clone());if(m.name==='B_WOOD'&&!woods.includes(m))woods.push(m);if(m.map)m.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(m.name.startsWith('B_ACCENT')&&!accent.includes(m))accent.push(m);if(m.name.startsWith('B_FABRIC')&&!fabric.includes(m))fabric.push(m);if(m.emissive.getHex()>0&&!emissives.some(e=>e.material===m))emissives.push({material:m,intensity:m.emissiveIntensity,color:m.emissive.clone()});if(m.transparent&&m.opacity<.8)o.castShadow=false;}});}});scene.add(asset);setMaterialAvailable(accent.length+fabric.length>0);setFurnitureObjects([...variantObjects]);furnitureGroups.forEach(group=>furniture(group,'contemporaneo'));changeTemperature(3000);lighting(16.5);try{const saved=JSON.parse(localStorage.getItem('eme-spatial.botanique.ambientacao.v1')||'null');if(isFurnitureVariant(saved?.sofa))furniture('sofa',saved.sofa);if(isFurnitureVariant(saved?.chairs))furniture('chairs',saved.chairs);for(const group of furnitureGroups){if(isFurnitureChoice(group,saved?.furniture?.[group]))furniture(group,saved.furniture[group]);}if(isLightTemperature(saved?.temperature))changeTemperature(saved.temperature);if(isBotaniquePalette(saved?.palette))changePalette(saved.palette);if(saved?.wood)finish('wood',saved.wood);if(saved?.fabric)finish('fabric',saved.fabric);if(Number.isFinite(saved?.indoor)){indoorPower=T.MathUtils.clamp(saved.indoor,0,1);setIndoor(indoorPower);daylight.setIndoor(indoorPower);}if(Number.isFinite(saved?.hour))lighting(T.MathUtils.clamp(saved.hour,7,20));}catch{/* A demonstration preference is optional. */}await prepareViewPrograms();if(disposed)return;loaded=true;daylight.setInteriorReady();setReady(true);renderer.shadowMap.needsUpdate=true;draw();
  }).catch(e=>{if(!disposed&&e.name!=='AbortError')setError(e.message||'Não foi possível abrir o modelo. Continue pelas imagens da apresentação.');}).finally(()=>draco.dispose());
  const onResize=()=>{if(!mount.clientWidth||!mount.clientHeight)return;camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();profile();};const observer=new ResizeObserver(onResize);observer.observe(mount);
  const visibility=()=>{previousContinuous=false;if(document.hidden){movement.x=movement.y=0;if(frame)cancelAnimationFrame(frame);frame=0;cancelTour();}else{last=performance.now();draw();}};const intersection=new IntersectionObserver(([entry])=>{previousContinuous=false;visible=entry.isIntersecting;if(!visible){if(frame)cancelAnimationFrame(frame);frame=0;cancelTour();}else draw();});intersection.observe(mount);
  const stop=()=>{movement.x=movement.y=0;stopWalk();flight=null;cancelTour();};controls.addEventListener('start',stop);controls.addEventListener('change',draw);document.addEventListener('visibilitychange',visibility);
  let pointer:{x:number;y:number;originX:number;originY:number;id:number;dragged:boolean}|null=null;
  const down=(event:PointerEvent)=>{if((!inRoom&&!topMode)||event.button!==0)return;if(pointer&&pointer.id!==event.pointerId){pointer.dragged=true;return;}stopWalk();flight=null;cancelTour();pointer={x:event.clientX,y:event.clientY,originX:event.clientX,originY:event.clientY,id:event.pointerId,dragged:false};renderer.domElement.setPointerCapture(event.pointerId);};
  const move=(event:PointerEvent)=>{if(!pointer||pointer.id!==event.pointerId)return;pointer.dragged=pointer.dragged||Math.hypot(event.clientX-pointer.originX,event.clientY-pointer.originY)>6;if(pointer.dragged&&inRoom){yaw-=(event.clientX-pointer.x)*.004;pitch=T.MathUtils.clamp(pitch-(event.clientY-pointer.y)*.004,-1.25,1.25);look();draw();}pointer.x=event.clientX;pointer.y=event.clientY;};
  const up=(event:PointerEvent)=>{if(pointer&&pointer.id===event.pointerId){const clicked=!pointer.dragged;pointer=null;if(renderer.domElement.hasPointerCapture(event.pointerId))renderer.domElement.releasePointerCapture(event.pointerId);if(clicked&&event.type==='pointerup'){if(topMode)planPick(event);else walkTo(event);}}};
  const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){stop();draw();}if(inRoom&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();stop();yaw+=(event.key==='ArrowLeft'?.07:event.key==='ArrowRight'?-.07:0);pitch=T.MathUtils.clamp(pitch+(event.key==='ArrowUp'?.05:event.key==='ArrowDown'?-.05:0),-1.15,1.15);look();draw();}};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('keydown',key);
  const contextLost=(event:Event)=>{event.preventDefault();stop();setError('O navegador interrompeu o 3D. Feche a experiência e abra novamente; as imagens continuam disponíveis.');};renderer.domElement.addEventListener('webglcontextlost',contextLost);
  const fullscreenChange=()=>{const native=document.fullscreenElement===container.current;if(native){expandedRef.current=true;setFull(true);}else if(expandedRef.current){expandedRef.current=false;setFull(false);}};document.addEventListener('fullscreenchange',fullscreenChange);
  const liveFrame=()=>{liveRequested=true;draw();},blur=()=>{movement.x=movement.y=0;};document.addEventListener('b-live-frame',liveFrame);document.addEventListener('b-recording-quality',profile);window.addEventListener('blur',blur);
  api.current={move:moveInput,redraw:draw,furniture,temperature:changeTemperature,view:select,home:()=>select(initial,apartment),top:plan,light:lighting,indoor:value=>{indoorPower=value;setIndoor(value);daylight.setIndoor(value);lighting(solarHour);},palette:changePalette,finish,walk:walkingMode,quality:value=>{qualityMode=value;profile();},zoom:direction=>{stop();if(inRoom){camera.fov=T.MathUtils.clamp(camera.fov+direction*6,40,80);camera.updateProjectionMatrix();}else{camera.position.sub(controls.target).multiplyScalar(direction>0?1.18:.84).add(controls.target);controls.update();}draw();},tour:enabled=>{if(!loaded)return;stopWalk();tourOn=enabled;setTour(enabled);tourIndex=0;tourAt=performance.now()-7000;if(enabled)draw();}};
  if(apartment){camera.fov=58;camera.updateProjectionMatrix();syncLook(tuple(definition.camera.target));}
  onResize();draw();
  return()=>{disposed=true;abort.abort();if(frame)cancelAnimationFrame(frame);timers.forEach(clearTimeout);api.current=null;observer.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',fullscreenChange);document.removeEventListener('b-live-frame',liveFrame);document.removeEventListener('b-recording-quality',profile);window.removeEventListener('blur',blur);controls.removeEventListener('start',stop);controls.removeEventListener('change',draw);controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('keydown',key);renderer.domElement.removeEventListener('webglcontextlost',contextLost);planContext?.dispose();daylight.dispose();visualRefinement?.dispose();post?.ao.dispose();post?.bloom.dispose();post?.render.dispose();post?.output.dispose();post?.composer.dispose();scene.traverse(o=>{if(o instanceof T.DirectionalLight||o instanceof T.SpotLight||o instanceof T.PointLight)o.shadow.dispose();});resources.forEach(r=>r.dispose());scene.clear();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();void last;void topMode;void solarHour;};
 },[kind,definition,apartment,rooms,views]);
 async function fullscreen(){
  if(full){expandedRef.current=false;setFull(false);if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});return;}
  expandedRef.current=true;setFull(true);
  try{if(container.current?.requestFullscreen&&document.fullscreenEnabled)await container.current.requestFullscreen();}catch{/* Safari and embedded browsers retain the full-viewport experience. */}
  if(document.fullscreenElement&&matchMedia('(pointer:coarse)').matches){const orientation=screen.orientation as ScreenOrientation&{lock?:(value:string)=>Promise<void>};void orientation?.lock?.('landscape').catch(()=>{});}
 }
 function save(){try{localStorage.setItem('eme-spatial.botanique.ambientacao.v1',JSON.stringify({furniture:selections,sofa:selections.sofa,chairs:selections.chairs,temperature,palette,wood:woodTone,fabric:fabricTone,hour,indoor,updatedAt:new Date().toISOString(),project:'botanique',type:'demonstration-preference'}));setSaved('Minha ambientação salva neste navegador.');const panel=container.current?.querySelector<HTMLDetailsElement>('.b-materials');if(panel)panel.open=false;}catch{setSaved('O navegador não permitiu salvar. Sua escolha continua nesta visita.');}}
 return <div className={'b-viewer '+(full?'b-immersive':'')} ref={container}><div className="b-canvas" ref={host}/><div className={'b-camera-fade '+(fade?'is-visible':'')}/>
  <BotaniqueRecorder ready={ready&&!error}/><div className="b-viewer-top"><div><span>{apartment?'APARTAMENTO DE ESTUDO':'BOTANIQUE HOME RESORT'}</span><strong>{view}</strong></div><button onClick={fullscreen} aria-label={full?'Sair da tela cheia':'Abrir tela cheia'}>{full?<X size={18}/>:<Expand size={18}/>}</button></div>
  <div className="b-view-pills" aria-label="Vistas do cenário">{views.map(point=><button key={point.id} disabled={!ready} aria-pressed={view===point.label} onClick={()=>api.current?.view(point,apartment)}>{point.label}</button>)}{apartment&&<button disabled={!ready} aria-pressed={view==='Planta 3D'} onClick={()=>api.current?.top()}><Layers size={14}/>Planta 3D</button>}</div>
  {!planActive&&(apartment||walking)&&places.length>0&&<details className="b-room-pills" open={roomsOpen} onToggle={e=>setRoomsOpen(e.currentTarget.open)}><summary><Home size={13}/>{apartment?'Explorar ambientes':'Áreas comuns'}<span>{places.length}</span></summary><div aria-label="Visitar ambientes">{places.map(room=><button key={room.id} disabled={!ready} aria-pressed={view===room.label} onClick={()=>{api.current?.view(room,true);setRoomsOpen(false);}}>{room.label}<ArrowRight size={13}/></button>)}</div></details>}

  {planActive&&<><div className="b-plan-card"><span>CORTE DO EDIFÍCIO</span><strong>{definition.floorContext?.label||'Pavimento-tipo · Final 1'}</strong><p>{definition.floorContext?.note||'Distribuição conforme a planta comercial. Dimensões e entorno estimados.'}</p><button onClick={()=>api.current?.top(!planDetail)}><Layers size={14}/>{planDetail?'Ver o pavimento':'Detalhar apartamento'}<ArrowRight size={14}/></button></div><div className="b-plan-labels" aria-label="Ambientes da planta">{[1,2,3,4,5,6,7,8].map(final=>final===1?<button key={final} ref={el=>{if(el)planLabels.current.set('final-1',el);else planLabels.current.delete('final-1');}} className="b-plan-unit-active" onClick={()=>api.current?.top(true)}>Final 1 · 55,55 m²<ArrowRight size={13}/></button>:<span key={final} ref={el=>{if(el)planLabels.current.set('final-'+final,el);else planLabels.current.delete('final-'+final);}}>Final {final}</span>)}{rooms.filter(r=>['living','kitchen','balcony'].includes(r.id)).map(room=><button key={room.id} ref={el=>{if(el)planLabels.current.set(room.id,el);else planLabels.current.delete(room.id);}} className="b-plan-room" aria-label={'Entrar em '+room.label+' pela planta'} onClick={()=>api.current?.view(room,true)}>{room.label}<ArrowRight size={13}/></button>)}</div></>}
  <div className="b-viewer-controls"><div className="b-controls-primary"><button disabled={!ready} aria-pressed={tour} onClick={()=>api.current?.tour(!tour)}>{tour?<Pause size={15}/>:<Play size={15}/>}<span>{tour?'Pausar visita':'Visita guiada'}</span></button><button disabled={!ready} aria-pressed={walking} onClick={()=>api.current?.walk(!walking)}><Footprints size={15}/><span>{walking?'Caminhando':'Passear'}</span></button>{!apartment&&<button className="b-enter-apartment" onClick={onEnterApartment}><Home size={15}/><span>Entrar no apartamento</span><ArrowRight size={14}/></button>}</div><div className="b-controls-secondary"><label><span>Qualidade</span><select value={quality} onChange={e=>{const q=e.target.value as Quality;setQuality(q);api.current?.quality(q);}}><option value="auto">Automática</option><option value="light">Leve</option><option value="high">Alta</option></select></label><button aria-label="Aproximar" disabled={!ready} onClick={()=>api.current?.zoom(-1)}><Plus size={17}/></button><button aria-label="Afastar" disabled={!ready} onClick={()=>api.current?.zoom(1)}><Minus size={17}/></button><button aria-label="Vista inicial" disabled={!ready} onClick={()=>api.current?.home()}><RotateCcw size={16}/></button></div></div>
  <div className="b-solar-control"><label htmlFor={'b-sun-'+kind}><Sun size={14}/><span>Horário do sol</span><output>{formatSolarHour(hour)}</output></label><input id={'b-sun-'+kind} aria-label="Horário do sol" type="range" min="7" max="20" step="0.25" value={hour} disabled={!ready} onChange={e=>api.current?.light(Number(e.target.value))}/><div><span>Manhã</span><span>Simulação visual</span><span>Noite</span></div></div><p className="b-viewer-help">{walkHint||(planActive?'Clique na Final 1 para aproximar · Escolha um ambiente para entrar.':roomMode?'Clique no piso para caminhar · Arraste para olhar · Esc para parar.':'Arraste para girar · Ative Passear para caminhar nas áreas comuns.')}</p>
  {apartment&&materialAvailable&&!planActive&&<details className="b-materials" onToggle={e=>{setMaterialsOpen(e.currentTarget.open);if(e.currentTarget.open){setRoomsOpen(false);api.current?.move(0,0);}}}><summary><Maximize2 size={14}/>Minha ambientação</summary><button className="b-material-close" aria-label="Fechar ambientação" onClick={()=>{const d=container.current?.querySelector<HTMLDetailsElement>('.b-materials');if(d)d.open=false;}}><X size={17}/></button><div className="b-material-scroll"><p>Experimente móveis, materiais e a luz do seu ambiente.</p><div className="b-palette-grid">{(Object.keys(palettes) as BotaniquePalette[]).map(p=><button key={p} aria-pressed={palette===p} onClick={()=>{api.current?.palette(p);setSaved('');}}><i style={{background:palettes[p].accent}}/><span>{palettes[p].label}</span>{palette===p&&<Check size={12}/>}</button>)}</div><div className="b-studio-section">Mobiliário e fornecedores</div><button className="b-catalog-launch" onClick={()=>openCatalog()}><Layers size={16}/><span>Explorar catálogo 3D<small>Móveis, luminárias e eletrodomésticos</small></span><ArrowRight size={15}/></button><div className="b-studio-section">Acabamentos</div><label className="b-finish-label">Madeira<select value={woodTone} onChange={e=>api.current?.finish('wood',e.target.value)}><option value="composicao" disabled>Da composição</option><option value="natural">Carvalho natural</option><option value="mel">Carvalho mel</option><option value="nogueira">Nogueira</option><option value="clara">Madeira clara</option></select></label><label className="b-finish-label">Estofados<select value={fabricTone} onChange={e=>api.current?.finish('fabric',e.target.value)}><option value="composicao" disabled>Da composição</option><option value="linho">Linho natural</option><option value="perola">Pérola</option><option value="oliva">Oliva</option><option value="terracota">Terracota</option></select></label><div className="b-studio-section">Iluminação</div><div className="b-temperature" role="group" aria-label="Temperatura da iluminação">{([3000,4000,6000] as LightTemperature[]).map(k=><button key={k} aria-pressed={temperature===k} onClick={()=>{api.current?.temperature(k);setSaved('');}}><i style={{background:temperatureColor[k]}}/><span>{k===3000?'Quente':k===4000?'Neutra':'Fria'}<small>{k.toLocaleString('pt-BR')} K</small></span></button>)}</div><label className="b-finish-label">Luzes internas<input aria-label="Intensidade das luzes internas" type="range" min="0" max="1" step=".05" value={indoor} onChange={e=>api.current?.indoor(Number(e.target.value))}/></label><button className="b-save-palette" onClick={save}><Save size={14}/>Salvar minha escolha</button><small>Preferência local · ambientação demonstrativa.</small></div></details>}
  {apartment&&ready&&!planActive&&!catalogOpen&&<button className="b-catalog-shortcut" onClick={()=>openCatalog()}><Layers size={15}/>Trocar móveis</button>}
  {apartment&&catalogOpen&&!planActive&&<BotaniqueFurnitureCatalog objects={furnitureObjects} group={catalogGroup} selections={selections} onGroupChange={group=>{if(isFurnitureGroup(group))setCatalogGroup(group);}} onSelect={(group,variant)=>{if(isFurnitureGroup(group)&&isFurnitureChoice(group,variant)){api.current?.furniture(group,variant);setSaved('');}}} onClose={()=>setCatalogOpen(false)}/>}
  <BotaniqueMobileControls ready={ready} apartment={apartment} walking={walking&&!planActive} blocked={catalogOpen||materialsOpen||!!error||!ready} full={full} view={view} views={views} rooms={places} hour={hour} quality={quality} tour={tour} onView={v=>api.current?.view(v,apartment||places.some(p=>p.id===v.id))} onPlan={()=>api.current?.top()} onCatalog={()=>openCatalog()} onMaterials={()=>{const d=container.current?.querySelector<HTMLDetailsElement>('.b-materials');if(d)d.open=true;}} onHour={v=>api.current?.light(v)} onQuality={q=>{setQuality(q);api.current?.quality(q);}} onWalk={()=>api.current?.walk(!walking)} onTour={()=>api.current?.tour(!tour)} onApartment={onEnterApartment} onMove={(x,y)=>api.current?.move(x,y)}/>
  {saved&&<p role="status" className="b-viewer-toast">{saved}<button aria-label="Fechar aviso" onClick={()=>setSaved('')}><X size={13}/></button></p>}
  {!ready&&!error&&<div className="b-viewer-loading" role="status"><LoaderCircle className="b-spinner-icon" size={26}/><strong>Preparando {apartment?'o apartamento':'o empreendimento'}…</strong><span>Carregando apenas este cenário.</span></div>}
  {error&&<div className="b-viewer-loading b-viewer-error" role="alert"><strong>Vamos continuar pelas imagens.</strong><p>{error}</p><a className="b-button" href="#imagens">Abrir galeria<ArrowRight size={15}/></a></div>}
 </div>;
}
